### ISSUE TITLE
[Bug]: Getting failure after upgrading from "^6.5.17-alpha.0" version to 7.0.8  "@storybook/react" version

### ISSUE THREAD

**Issue by Annniee1** [storybookjs/storybook#23346]
### Describe the bug

Getting following failure

error TS2307: Cannot find module '@storybook/react/types-6-0' or its corresponding type declarations.
ERR! 
ERR! 1 import { Meta } from "@storybook/react/types-6-0";
ERR!                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERR! 
ERR! src/Ribbon/Ribbon.stories.tsx:2:29 - error TS2307: Cannot find module '@storybook/react/types-6-0' or its corresponding type declarations.
ERR! 
ERR! 2 import { Story, Meta } from "@storybook/react/types-6-0";
ERR!                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Annniee1** [comment]
@paulrosania @Peeja @theshortcut @theinterned  Can you please suggest something to resolve
