### ISSUE TITLE
[Bug]: Unable to start Storybook 6.5.x for react after upgrade Typescript to 5.+

### ISSUE THREAD

**Issue by annidai** [storybookjs/storybook#21642]
### Describe the bug

I'm currently on Storybook `6.5.16` for React.
After upgrading Typescript to version `5.0.2`, the following errors are throwing when I start storybook:
```
70% sealing plugins DocGenPlugin/dev/node_modules/@storybook/react-docgen-typescript-plugin/dist/generateDocgenCodeBlock.js:37
    return insertTsIgnoreBeforeStatement(typescript_1.default.createExpressionStatement(typescript_1.default.createBinary(typescript_1.default.createPropertyAccess(typescript_1.default.createIdentifier(d.displayName), typescript_1.default.createIdentifier("displayName")), typescript_1.default.SyntaxKind.EqualsToken, typescript_1.default.createLiteral(d.displayName))));
                                                                                                                                                                                         ^

TypeError: typescript_1.default.createIdentifier is not a function
    at setDisplayName (/dev/node_modules/@storybook/react-docgen-typescript-plugin/dist/generateDocgenCodeBlock.js:37:186)
```

### To Reproduce
clone https://github.com/annidai/default-ts
yarn && yarn storybook

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.18.1 - ~/.volta/tools/image/node/16.18.1/bin/node
    Yarn: 1.22.19 - ~/Development/eblock-web/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/16.18.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0
    Safari: 16.2
  npmPackages:
    @storybook/addon-actions: 6.5.16 => 6.5.16 
    @storybook/addon-console: 1.2.3 => 1.2.3 
    @storybook/addon-essentials: 6.5.16 => 6.5.16 
    @storybook/addon-links: 6.5.16 => 6.5.16 
    @storybook/builder-webpack5: 6.5.16 => 6.5.16 
    @storybook/manager-webpack5: 6.5.16 => 6.5.16 
    @storybook/node-logger: 6.5.16 => 6.5.16 
    @storybook/react: 6.5.16 => 6.5.16
```

**Comment by andreigec** [comment]
Workarounds:

package json:
```json
"resolutions": {
    "@storybook/react-docgen-typescript-plugin": "1.0.6--canary.9.cd77847.0"
  },

"scripts": {
  "build-storybook": "cross-env NODE_OPTIONS=--openssl-legacy-provider build-storybook"
}
```

**Comment by annidai** [comment]
> Workarounds:
> 
> package json:
> 
> ```json
> "resolutions": {
>     "@storybook/react-docgen-typescript-plugin": "1.0.6--canary.9.cd77847.0"
>   },
> 
> "scripts": {
>   "build-storybook": "cross-env NODE_OPTIONS=--openssl-legacy-provider build-storybook"
> }
> ```

Works perfectly! Thanks!

Is this fixed with the Storybook 7.+?

**Comment by VGalata** [comment]
See also here: https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/78#issuecomment-1409224863.

The solution provided there worked for me when dealing with the issue described by the OP.

**Comment by shilman** [comment]
I think this is fixed in 7.0 already. Can anybody please try upgrading & report back? Many thanks! 🙏 

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by shilman** [comment]
@ryami333 Storybook 7 is in RC so if it works there then that would be useful info to know. I doubt we'll fix in 6.5

**Comment by literalpie** [comment]
I have a private React project that fails to start with SB 6.5+TS 5.0, and succeeds with SB 7+TS 5.0 (and SB 6.5+TS 4.9)

**Comment by hyochan** [comment]
What if we can't upgrade to Storybook 7.0 since we are using React Native storybook?

https://github.com/dooboolab/dooboo-ui/actions/runs/4461816661/jobs/7835929160

**Comment by hyochan** [comment]
> Workarounds:
> 
> package json:
> 
> ```json
> "resolutions": {
>     "@storybook/react-docgen-typescript-plugin": "1.0.6--canary.9.cd77847.0"
>   },
> 
> "scripts": {
>   "build-storybook": "cross-env NODE_OPTIONS=--openssl-legacy-provider build-storybook"
> }
> ```

Thanks the resolution worked to solve the issue here https://github.com/dooboolab/dooboo-ui/actions/runs/4461816661/jobs/7835929160

**Comment by lauriharpf** [comment]
> Workarounds:
> 
> package json:
> 
> ```json
> "resolutions": {
>     "@storybook/react-docgen-typescript-plugin": "1.0.6--canary.9.cd77847.0"
>   },
> 
> "scripts": {
>   "build-storybook": "cross-env NODE_OPTIONS=--openssl-legacy-provider build-storybook"
> }
> ```

Great workaround! :+1: With Node v18.14.1, Typescript 5.0.2 and @storybook/react 6.5.16, just adding

```json
"resolutions": {
     "@storybook/react-docgen-typescript-plugin": "1.0.6--canary.9.cd77847.0"
},
```

seems to be enough to fix the build. I'm not sure whether `cross-env NODE_OPTIONS=--openssl-legacy-provider` is necessary 🤔.

**Comment by shilman** [comment]
Ta-da!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.17-alpha.0 containing PR #21745 that references this issue. Upgrade today to the `@prerelease` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by mrharispe** [comment]
@shilman are there any further steps other than updating the package?

With this prerelease package, Storybook starts without errors, but the controls from 3rd party libs are gone (it was working for me with Storybook 6.5 and TypeScript 4).

What I mean by 3rd party is that I'm wrapping MUI components (which use `forwardRef`, not sure if that's relevant but I saw that there are other tickets about `forwardRef` and Storybook 7, like #21686)

Here's an example:
```
import {
  Breadcrumbs as MuiBreadcrumbs,
  BreadcrumbsProps as MuiBreadcrumbsProps,
} from '@mui/material'
import { forwardRef } from 'react'

export type BreadcrumbsProps = MuiBreadcrumbsProps

const Breadcrumbs = forwardRef<HTMLElement, BreadcrumbsProps>(
  ({ ...props }, ref) => <MuiBreadcrumbs ref={ref} {...props} />,
)

export default Breadcrumbs
```

A simple Story that loads this Breadcrumbs component gives me "No inputs found for this component"

My `main.js` has `reactDocgen: 'react-docgen-typescript'` set, which was working with TypeScript 4

**Comment by SiddharthaChowdhury** [comment]
> See also here: [hipstersmoothie/react-docgen-typescript-plugin#78 (comment)](https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/78#issuecomment-1409224863).
> 
> The solution provided there worked for me when dealing with the issue.

This worked for me! Thanks!

**Comment by shilman** [comment]
@mrharispe that's why it's a prerelease. we are still flushing out the bugs in the new version of the package.

**Comment by mrharispe** [comment]
> @mrharispe that's why it's a prerelease. we are still flushing out the bugs in the new version of the package.

And that's why I'm commenting, to try to help the Storybook team figure out bugs before GA. Simply giving repro steps to what I think is a bug, please don't take it the wrong way, I can't wait to use Storybook 7!

**Comment by dbrackma** [comment]
I can confirm that this is _**not fixed**_ with the combination of SB 7.0.7 and TS 5.0.4.

`ModuleBuildError: Module build failed (from ../../node_modules/react-docgen-typescript-loader/dist/index.js):`
`TypeError: typescript_1.default.createIdentifier is not a function`
`    at setDisplayName (/home/opc/jet/node_modules/react-docgen-typescript-loader/dist/generateDocgenCodeBlock.js:62:174)`
`    at /home/opc/jet/node_modules/react-docgen-typescript-loader/dist/generateDocgenCodeBlock.js:38:32`
`    ...`

**Comment by RodrigoTomeES** [comment]
The issue persist with Storybook 7.1

**Comment by caiocaprio** [comment]
What would be the solution? 
I still have the problem!

**Comment by TerrySlack** [comment]
@caiocaprio 
Here is a link to a working repo with Storybook 7.1.1, Typescript, and Webpack.   Hope this helps

https://github.com/TerrySlack/WebPack-5-React-Typescript-BoilerPlate

**Comment by jenskuhrjorgensen** [comment]
@shilman seems like the alpha release fixes my issue too - thanks a lot!

But, why was it never released in a proper v6.5.17 release instead of an alpha release?
