### ISSUE TITLE
Angular-cli example fails to build/run

### ISSUE THREAD

**Issue by Steven-Harris** [storybookjs/storybook#10667]
**Describe the bug**
The main issue is that the example angular-cli fails to build and I can't run it. I was having issues getting storybook to pick up the compodoc json file and it doesn't seem to work with 5.3.18

**To Reproduce**
1. run example angular-cli app in master branch. (doesn't work in @next either)

**Error**
```
λ npx build-storybook -s src/assets
Cannot find module '../dist/server/build'
``` 

**System:**
```
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 12.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```

**Comment by Steven-Harris** [comment]
nevermind, figured out I need to bootstrap the application from the root package.json
