### PR TITLE
Fix TS5 support in 6.5

### LINKED ISSUE #21642: [Bug]: Unable to start Storybook 6.5.x for react after upgrade Typescript to 5.+
### Describe the bug

I'm currently on Storybook `6.5.16` for React.
After upgrading Typescript to version `5.0.2`, the following errors are throwing when I start storybook:
```
70% sealing plugins DocGenPlugin/dev/node_modules/@storybook/react-docgen-typescript-plugin/dist/generateDocgenCodeBlock.js:37
    return insertTsIgnoreBeforeStatement(typescript_1.default.createExpressionStatement(typescript_1.default.createBinary(typescript_1.default.createPropertyAccess(typescript_1.default.createIdentifier(d.displayName), typescript_1.default.createIdentifier("displayName")), typescript_1.default.SyntaxKind.EqualsToken, typescript_1.default.createLiteral(d.displayName))));
                                                                                                                                                                                         ^

TypeError: typescript_1.default.createIdentifier is not a function
    at setDisplayName (/dev/node_modules/@storybook/react-docgen-typescript-plugin/dist/generateDocgenCodeBlock.js:37:186)
```

### To Reproduce
clone https://github.com/annidai/default-ts
yarn && yarn storybook

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.18.1 - ~/.volta/tools/image/node/16.18.1/bin/node
    Yarn: 1.22.19 - ~/Development/eblock-web/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/16.18.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0
    Safari: 16.2
  npmPackages:
    @storybook/addon-actions: 6.5.16 => 6.5.16 
    @storybook/addon-console: 1.2.3 => 1.2.3 
    @storybook/addon-essentials: 6.5.16 => 6.5.16 
    @storybook/addon-links: 6.5.16 => 6.5.16 
    @storybook/builder-webpack5: 6.5.16 => 6.5.16 
    @storybook/manager-webpack5: 6.5.16 => 6.5.16 
    @storybook/node-logger: 6.5.16 => 6.5.16 
    @storybook/react: 6.5.16 => 6.5.16
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shilman**
Closes #21642

## What I did

Upgrade `react-docgen-typescript-plugin` to a version that is TS5 compatible

## How to test

Upgrade a React sandbox to TS5 and run Storybook?

### CODE REVIEW

**Comment by catherine** [comment]
I'm also wondering if there is a plan to release this in a non-alpha version?

**Comment by lanesawyer** [comment]
Wanted to leave another comment, as a release for this would be much appreciated but I'm not seeing much traction.

For those of us who can't upgrade to Storybook 7 (for me team, we don't use Vite or Webpack so Storybook 7 is unbuildable unless we discard our build tool, Parcel), this is an important v6 release to allow us to keep upgrading our TypeScript version in our repositories.

Without this, we are unable to upgrade a variety of libraries we used due to TS being halted at 4.9.3 because of the lack of Storybook v6 support for TS 5+.

I'd love to get to Storybook 7 but I'm sure there are many other projects out there in a similar situation where we simply can't make the major version jump (yet).

I'm going to try running the alpha release and we'll use that long-term if necessary, but I'm not a big fan of the dependency warnings in the console that (as far as I can tell) are only there because the alpha tag doesn't follow semver so the packages think there is a problem.
