### PR TITLE
Core: Fix channel options so that they are merged in correct order

### LINKED ISSUE #12364: CSP: Storybook 6 uses unsafe-eval
## Description
A react component library I maintain for my company deploys a storybook to our internal Github Pages (enterprise). These have headers that set a Content Security Policy (CSP) that does **not** include `unsafe-eval`. These cannot be overwritten by `<meta .../>` tags as the headers have a stricter policy.

After upgrading Storybook 5.3.9 to 6.0.21, the storybook will not load any more:
```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

Uncaught TypeError: __webpack_require__(...) is not a function
``` 
Expanded screenshot below.

The problem is reproduce-able locally with a minimal config, but the original issue is with a built version on a remote server.

### Setup minimal storybook react
1. `mkdir test-sb && cd test-sb`
2. `yarn init`
3. `yarn add react react-dom`
4. `npx sb init`

### Emulate CSP & run
1. `echo "<meta
  http-equiv=\"Content-Security-Policy\"
  content=\"default-src 'self' ; script-src 'self' 'unsafe-inline';
style-src 'self' 'unsafe-inline'; img-src 'self' *; media-src 'self' ; frame-src 'self';\"
/>" > .storybook/manager-head.html`
2. `yarn storybook`

## Expected behavior
As previous versions, Storybook should avoid leveraging `unsafe-eval`

## Screenshot
Screen Shot 2020-09-02 at 5 26 28 PM

## System
Local setup
  ```System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.0.21 => 6.0.21 
    @storybook/addon-essentials: ^6.0.21 => 6.0.21 
    @storybook/addon-links: ^6.0.21 => 6.0.21 
    @storybook/react: ^6.0.21 => 6.0.21 ```

### PR DESCRIPTION
**Pull request by ndelangen**
Issue: https://github.com/storybookjs/storybook/issues/12364

## What I did

The options were merged incorrectly, making the default be preserved over the configured options by the user.

## How to test

- [ ] Is this testable with Jest or Chromatic screenshots?
- [ ] Does this need a new example in the kitchen sink apps?
- [ ] Does this need an update to the documentation?

### CODE REVIEW

**Review by gjou-tlnd — APPROVED** [review]

File: lib/channel-postmessage/src/index.ts [hunk 1]
```diff
@@ -87,7 +87,11 @@ export class PostmsgTransport {
       }).filter(([k, v]) => typeof v !== 'undefined')
     );
 
-    const stringifyOptions = { ...(global.CHANNEL_OPTIONS || {}), ...c };
+    const stringifyOptions = {
+      ...{ allowFunction: true, maxDepth: 25 },
```
Comment (yannbf) [inline lib/channel-postmessage/src/index.ts:91]: Do we want to have an object that states what these are? like `const sensibleDefaults` or something? And maybe we can rename `c` to something that is more explanatory?

**Review by shilman — APPROVED** [review]
LGTM! 🙏
