### ISSUE TITLE
Storybook is adding displayName and __docgenInfo to my exported TS enum

### ISSUE THREAD

**Issue by lgraziani2712** [storybookjs/storybook#9832]
**Describe the bug**

I have an **enum** in some file. When I imported it to the story, it adds extra props to it, making it impossible to use with **Object.values()** because it will have those extra props too.

**To Reproduce**

1. Export an enum with some props.
2. Try to render a story where you use the values of that enum.
3. See error

**Expected behavior**
To not have extra props when using the enum.

**Screenshots**
![image](https://user-images.githubusercontent.com/15050200/74367103-0e6f9d00-4db0-11ea-83a3-cf4f7d0abfb0.png).

**Code snippets**
```tsx
// someSiblingFile.ts
export enum EnumWithExtraProps {
  key1 = 'key1',
  key2 = 'key2',
}

// a.story.tsx
import { EnumWithExtraProps } from './someSiblingFile.ts';

const mapWithText: { [key in EnumWithExtraProps ]: string } = {
  key1: ['Title for key1', 'Description for key1'],
  key2: ['Title for key2', 'Description for key2'],
};

export function Story() {
  return (
    <>
      {Object.values(EnumWithExtraProps).map(type => {
        const a = mapWithText[type];

        // It will throw an error for "displayName" and "__docgenInfo" keys
        return <p>{a.join(' ')}</p>;
      })}
    </>
  );
}

```
**System:**
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.100
    Firefox: 74.0b2
  npmPackages:
    @storybook/addon-actions: 5.3.12 => 5.3.12 
    @storybook/addon-docs: 5.3.12 => 5.3.12 
    @storybook/addon-knobs: 5.3.12 => 5.3.12 
    @storybook/preset-typescript: 1.2.0 => 1.2.0 
    @storybook/react: 5.3.12 => 5.3.12
```

**Comment by shilman** [comment]
I'm updating all of that in 6.0; let's see how the new flow works.

**Comment by shilman** [comment]
Repro: https://github.com/storybookjs/storybook/commit/3e90384ca63c75a9c8c1367db484c656dd11e164

This seems to be fixed when we switch to react-docgen as part of #9837

**Comment by shilman** [comment]
@lgraziani2712 can you try the recommended 6.0 setup (should work in 5.3 too) and based on the repro linked above I expect the problem to be fixed:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#react-prop-tables-with-typescript

**Comment by joshcummingsdesign** [comment]
This still issue still exists with a clean installation of 5.3.19

```
"@storybook/addon-actions": "^5.3.19",
"@storybook/addon-knobs": "^5.3.19",
"@storybook/addon-links": "^5.3.19",
"@storybook/addons": "^5.3.19",
"@storybook/preset-create-react-app": "^3.0.0",
"@storybook/react": "^5.3.19",
```

**Comment by shilman** [comment]
@joshcummingsdesign is it fixed in 6.0-beta?

**Comment by lgraziani2712** [comment]
Now I'm working to update our SB to v6 because an update of a dependency made SB v5.3 crash because `core-js`. (v6 fixed it), so I'm going to check it and report it!

**Comment by lgraziani2712** [comment]
I can confirm that it is fixed in the v6-beta ^_^

**Comment by jldmn** [comment]
I'm having the same Error again in v6.0.7 :(

**Comment by shilman** [comment]
Here's what I said above:

> This seems to be fixed when we switch to react-docgen as part of #9837

Well, it turns out that we switched back to `react-docgen-typescript` for a variety of reasons, chief of which is support for imported types. If you can live without imported types you can try setting `module.exports = { typescript: { reactDocgen: 'react-docgen' }};` in your `.storybook/main.js` file. See https://storybook.js.org/docs/react/configure/typescript 

Reopening this issue. @hipstersmoothie any idea what's going on here?

**Comment by hipstersmoothie** [comment]
Could I get a reproduction repo?

**Comment by hipstersmoothie** [comment]
Currently not able to reproduce via tests for `react-docgen-typescript`

**Comment by hipstersmoothie** [comment]
@shilman what do I need to do to make the test you referenced above to use `react-docgen-typescript`

**Comment by hipstersmoothie** [comment]
I'm not sure this is an issue anymore. I put @lgraziani2712's code into my storybook and it doesn't add the docgen information to the exported enum

<img width="1089" alt="Screen Shot 2020-10-23 at 12 20 41 PM" src="https://user-images.githubusercontent.com/1192452/97045189-2ba55f80-152a-11eb-9e6c-88a89344d323.png">

**Comment by lgraziani2712** [comment]
Right now I'm working with storybook `v6.1.10` and I can confirm this bug is fixed!

**Comment by laustdeleuran** [comment]
Seeing this on Storybook `v6.2.8` as well. Unfortunately don't have the bandwidth to set up a clean repo to reproduce. It's in a fairly complex Gatsby (v3) + Contentful app.

**Comment by astorije** [comment]
Issue still persists on v6.3.2

**Comment by jiajzhou** [comment]
The issue still repro in 6.3.7. Switching to 'react-docgen' mitigates the issue. However, it has a worse error handling mechanism compared to react-docgen-typescript. react-docgen-typescript will show a detailed compilation error message when doing quick prototyping, while react-docgen will just render a whitescreen. I haven't noticed other difference yet, but the error handling is a quite big deal to me. So, really not an ideal solution.

**Comment by jasperdunn** [comment]
Seeing this on storybook v7.0.0-alpha

But with importing objects instead.

```ts
// ------ exported object from a file
export const color = {
  red: 'red',
  blue: 'blue',
  green: 'green',
};

// ------- story
import { color } from './color';

consolge.log({colors: Object.entries(color) });

// story code ....
```

When logging, these two properties are appearing in my array

**Comment by Faxxiz** [comment]
Still here in 8.3.6
Switching to react-docgen removes the issue, but have lots of issue on controls. react-docgen-typescript fixes a lot of those but have displayName and __docgenInfo generated ...

**Comment by eliskaachee** [comment]
> Just ran into this issue on `7.6.17`. The issue disappeared after removing the JSdoc comment from the enum in question.

Just ran into this issue in 8.0.6. A normal comment above the enum is fine, but a block comment above the enum generates the extra fields. I removed my block comment, and now works as expected.
