### ISSUE TITLE
[Bug]: Update Jest in @storybook/addon-storyshots-puppeteer for compatibility with latest version of puppeteer

### ISSUE THREAD

**Issue by ahayes91** [storybookjs/storybook#20479]
### Describe the bug

Very similar to https://github.com/puppeteer/puppeteer/issues/9121 - when we update Puppeteer from v18.1.0 to v18.2.1 we get an error in our Storyshot tests like the following:

```
[2022-12-30T00:20:52.134Z] FAIL Storyshot.test.js
[2022-12-30T00:20:52.134Z]   ● Test suite failed to run
[2022-12-30T00:20:52.134Z] 
[2022-12-30T00:20:52.134Z]     Cannot find module 'puppeteer-core/internal/common/DeviceDescriptors.js' from 'packages/learning-web/node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js'
[2022-12-30T00:20:52.134Z] 
[2022-12-30T00:20:52.134Z]     Require stack:
[2022-12-30T00:20:52.134Z]       node_modules/puppeteer/lib/cjs/puppeteer/puppeteer.js
[2022-12-30T00:20:52.134Z]       src/__tests__/Storyshot.test.js
[2022-12-30T00:20:52.134Z] 
[2022-12-30T00:20:52.134Z]       3 | import { imageSnapshot } from '@storybook/addon-storyshots-puppeteer';
[2022-12-30T00:20:52.134Z]       4 | import fetch from 'node-fetch';
[2022-12-30T00:20:52.134Z]     > 5 | import puppeteer from 'puppeteer';
[2022-12-30T00:20:52.134Z]         | ^
[2022-12-30T00:20:52.134Z]       6 |
[2022-12-30T00:20:52.134Z]       7 | process.env.staticStore = '.';
[2022-12-30T00:20:52.134Z]       8 |
[2022-12-30T00:20:52.134Z] 
[2022-12-30T00:20:52.134Z]       at Resolver._throwModNotFoundError (node_modules/jest-runtime/node_modules/jest-resolve/build/resolver.js:425:11)
[2022-12-30T00:20:52.134Z]       at Object.<anonymous> (packages/learning-web/node_modules/puppeteer/src/puppeteer.ts:18:1)
[2022-12-30T00:20:52.134Z]       at Object.<anonymous> (packages/learning-web/src/__tests__/Storyshot.test.js:5:1)
[2022-12-30T00:20:52.134Z]           at runMicrotasks (<anonymous>)
[2022-12-30T00:20:52.134Z] 
[2022-12-30T00:20:52.134Z] Test Suites: 1 failed, 1 total
```

From looking at https://github.com/puppeteer/puppeteer/issues/9121 and running `npm list jest` in our repo, we can see that Jest is on a lower version in the latest version of the addon:

```
├─┬ @storybook/addon-storyshots-puppeteer@6.5.15
│ └─┬ jest-image-snapshot@4.5.1
│   └── jest@27.5.1
```

If I get a chance I'll create a full repro for this ticket, but wanted to raise this in the meantime anyway in case other folks are seeing the same issue (and hopefully updating Jest is an easy fix).

**Comment by jonniebigodes** [comment]
The Storyshots addon is officially deprecated and will be removed in a future release of Storybook. To help with the transition process, we've created a [migration guide](https://storybook.js.org/docs/writing-tests/storyshots-migration-guide) for the available options and common use cases.
