### ISSUE TITLE
previewBuilder.bail is not a function

### ISSUE THREAD

**Issue by melocule** [storybookjs/storybook#19349]
Hey! I recently upgraded from v7.0.0-alpha.3*3* -> .3*4* in order to get around a bug that was patched with [this PR](https://github.com/storybookjs/storybook/pull/19123). `npm run storybook` worked great when this patch was added locally.

After upgrading however, a new error appears when I try to run Storybook saying that `previewBuilder.bail is not a function` at `@storybook/core-server/dist/cjs/dev-server.js:216:91`. 

I got the same error when I tried:
- Removing `node_modules` and running `npm install` again
- Reverting the repo to a state before Storybook and doing `npx storybook init` again

Using `@storybook/cli v7.0.0-alpha.34`, here's the full error (path to the repo is shortened to `./`):
```
info => Starting manager..
✘ [ERROR] Invalid option in build() call: "jsxImportSource"

    ./node_modules/esbuild/lib/main.js:244:12:
      244 │       throw new Error(`Invalid option ${where}: "${key}"`);
          ╵             ^

    at checkForInvalidFlags (./node_modules/esbuild/lib/main.js:244:13)
    at flagsForBuildOptions (./node_modules/esbuild/lib/main.js:429:3)
    at buildOrServeContinue (./node_modules/esbuild/lib/main.js:1219:9)
    at ./node_modules/esbuild/lib/main.js:1146:15

ERR! TypeError: previewBuilder.bail is not a function
ERR!     at ./node_modules/@storybook/core-server/dist/cjs/dev-server.js:216:91
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async Promise.all (index 1)
ERR!     at async storybookDevServer (./node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (./node_modules/@storybook/core-server/dist/cjs/build-dev.js:129:31)
ERR!     at async fn (./node_modules/@storybook/cli/dist/generate.js:254:1900)
ERR!  TypeError: previewBuilder.bail is not a function
ERR!     at ./node_modules/@storybook/core-server/dist/cjs/dev-server.js:216:91
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!     at async Promise.all (index 1)
ERR!     at async storybookDevServer (./node_modules/@storybook/core-server/dist/cjs/dev-server.js:207:28)
ERR!     at async buildDevStandalone (./node_modules/@storybook/core-server/dist/cjs/build-dev.js:129:31)
ERR!     at async fn (./node_modules/@storybook/cli/dist/generate.js:254:1900)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**System**
Results of `npx sb@next info`:
```
Environment Info:

  System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
    npm: 8.19.1 - ~/.nvm/versions/node/v18.9.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 16.0
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-alpha.34 => 7.0.0-alpha.34 
    @storybook/addon-interactions: ^7.0.0-alpha.34 => 7.0.0-alpha.34 
    @storybook/addon-links: ^7.0.0-alpha.34 => 7.0.0-alpha.34 
    @storybook/react: ^7.0.0-alpha.34 => 7.0.0-alpha.34 
    @storybook/react-vite: ^7.0.0-alpha.34 => 7.0.0-alpha.34 
    @storybook/testing-library: ^0.0.13 => 0.0.13 
```

**Comment by geodn** [comment]
I'm encountering the same issue when upgrading storybook-addon-mock from 2.4.1 to 3.1.0. `start-storybook` prints this error on the first run, but on subsequent runs, the storybook starts working.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.38 containing PR #19405 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by MarceloArraes** [comment]
The error remains for me..

**Comment by shilman** [comment]
@MarceloArraes do you have a reproduction you can share?

**Comment by MarceloArraes** [comment]
The repository is trying to deploy on githubpages here:
https://github.com/MarceloArraes/react-design-system

The error is like this:
`
npm run storybook

> react-ds@0.0.0 storybook
> start-storybook -p 6006

info @storybook/react v6.5.13
info 
info => Loading presets
attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://storybook.js.org/telemetry


info => Ignoring cached manager due to change in manager config
ERR! TypeError: previewBuilder.bail is not a function
ERR!     at /home/marcelo/designSystem/react-ds/node_modules/@storybook/core-server/dist/cjs/dev-server.js:212:26
ERR!     at async Promise.all (index 1)
ERR!     at async storybookDevServer (/home/marcelo/designSystem/react-ds/node_modules/@storybook/core-server/dist/cjs/dev-server.js:203:28)
ERR!     at async buildDevStandalone (/home/marcelo/designSystem/react-ds/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/home/marcelo/designSystem/react-ds/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)
ERR!  TypeError: previewBuilder.bail is not a function
ERR!     at /home/marcelo/designSystem/react-ds/node_modules/@storybook/core-server/dist/cjs/dev-server.js:212:26
ERR!     at async Promise.all (index 1)
ERR!     at async storybookDevServer (/home/marcelo/designSystem/react-ds/node_modules/@storybook/core-server/dist/cjs/dev-server.js:203:28)
ERR!     at async buildDevStandalone (/home/marcelo/designSystem/react-ds/node_modules/@storybook/core-server/dist/cjs/build-dev.js:120:31)
ERR!     at async buildDev (/home/marcelo/designSystem/react-ds/node_modules/@storybook/core-server/dist/cjs/build-dev.js:174:5)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.`

**Comment by shilman** [comment]
@MarceloArraes looks like this was only released in 7.0-alpha per my comment above. I'm not sure about the release schedule for the stable version, but maybe @ianvs or @joshwooding can comment here

**Comment by MarceloArraes** [comment]
Yes yes, i'm sorry. I sended you the wrong error. When I update to your alpha i get this:

`react-ds@0.0.0 build-storybook
> build-storybook

/tmp/build-storybook-3b3eca9[8](https://github.com/MarceloArraes/react-design-system/actions/runs/3312508880/jobs/5469259924#step:5:9).sh: 1: build-storybook: not found`

**Comment by shilman** [comment]
@MarceloArraes migration notes here

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#start-storybook--build-storybook-binaries-removed

We'll be adding an automigration to do this automatically, but for now you need to do it by hand. There might be some other useful migration notes there as well.

**Comment by joshwooding** [comment]
@MarceloArraes 0.2.5 has been released which should fix this if you're on v6
