### ISSUE TITLE
[Bug]: Storybook/HTML upgrade to v8 - Vite internal server error: this.getData is not a function

### ISSUE THREAD

**Issue by basher** [storybookjs/storybook#26581]
### Describe the bug

After migrating from Storybook/HTML v7 to v8, I get the following error in Node console:

```
11:03:34 [vite] Internal server error: this.getData is not a function
  Plugin: storybook:mdx-plugin
  File: C:/Users/kev/Documents/work/Projects/storybook7-html-minimal/stories/Components/Button.mdx
```
  
I've added a `vite.config.js` as documented here - https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#framework-specific-vite-plugins-have-to-be-explicitly-added

However, there's does NOT appear to be an html-specific plugin, so I've had to comment it out in my config:

```javascript
import { defineConfig } from 'vite';
// import html from '@vitejs/plugin-html';

export default defineConfig({
//   plugins: [html()],
});
```

Here are screenshots of Storybook UI errors for MDX and stories:

![MDX error](https://github.com/storybookjs/storybook/assets/452809/d4431aed-929c-4651-bb87-7cb2cf624650)
![story error](https://github.com/storybookjs/storybook/assets/452809/8bf819bf-d1ff-4117-843d-03148db2d799)

### To Reproduce

Here's my Storybook/HTML v7 minimal repo, with a new feature branch "**sb8-upgrade**" that demonstrates the issue:

https://github.com/basher/storybook7-html-minimal/tree/sb8-upgrade

### System

```bash
Storybook Environment Info:

  System:
    OS: Windows 10 10.0.19045    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE      
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD <----- active
  Browsers:
    Chrome: 122.0.6261.129
    Edge: Chromium (122.0.23)  npmPackages:
    @storybook/addon-a11y: ^8.0.2 => 8.0.2
    @storybook/addon-essentials: ^8.0.2 => 8.0.2
    @storybook/addon-links: ^8.0.2 => 8.0.2
    @storybook/blocks: ^8.0.2 => 8.0.2
    @storybook/html: ^8.0.2 => 8.0.2
    @storybook/html-vite: ^8.0.2 => 8.0.2
    storybook: ^8.0.2 => 8.0.2
```

**Comment by Lukas742** [comment]
Hi @basher,

we had the same issue after updating to v8 and we fixed it by upgrading `remark-gfm` to v4. Although, our setups are most probably pretty different, it might do the trick for you too.

**Comment by basher** [comment]
Thanks @Lukas742 - that worked!

I've also deleted `vite.config.js` as it's clearly not needed for Storybook/HTML.

My feature branch is now merged into `main`, and I have renamed my repo to https://github.com/basher/storybook8-html-minimal

**Comment by basher** [comment]
Thanks @Lukas742 - that worked!

I've also deleted `vite.config.js` as it's clearly not needed for Storybook/HTML.

My feature branch is now merged into `main`, and I have renamed my repo to https://github.com/basher/storybook8-html-minimal

**Comment by ginnymin** [comment]
When we upgraded `remark-gfm`, we got this TS error for the `import remarkGfm from 'remark-gfm'` in `main.ts`

`The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("remark-gfm")' call instead.`

Is there something we can do to resolve that TS error?

**Comment by basher** [comment]
@ginnymin I would open a new issue, as this is not directly related to my initial issue, which is now closed.
