### ISSUE TITLE
Errors after installing preset-create-react-app

### ISSUE THREAD

**Issue by thany** [storybookjs/storybook#14166]
**Describe the bug**
I've been getting this warning when starting Storybook since we upgraded to 6.0:
```
WARN Storybook support for Create React App is now a separate preset.
WARN To use the new preset, install `@storybook/preset-create-react-app` and add it to the list of `addons` in your `.storybook/main.js` config file.
WARN The built-in preset has been disabled in Storybook 6.0.
```
I did what it says, and now I'm getting compilation errors:
```
ERROR in ./src/Documentation/atomic-design.stories.mdx
Module not found: Error: You attempted to import /Coding-Guidelines/Atomic-Design/README.md which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
 @ ./src/Documentation/atomic-design.stories.mdx 12:0-65 27:13-16
 @ ./src sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(jsx|mdx))$
 @ ./config/storybook/generated-stories-entry.js
 @ multi ./node_modules/react-scripts/node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/react-scripts/node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./config/storybook/storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/a11yRunner.js-generated-other-entry.js ./node_modules/@storybook/addon-a11y/dist/a11yHighlight.js-generated-other-entry.js ./config/storybook/preview.jsx-generated-config-entry.js ./config/storybook/generated-stories-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined
```
This worked fine before. I cannot change the structure of our project, other components depend on it being the way it is, which is fine. Adding symbolic links is also a no-go, because first of all it says to create them in `node_modules`, which is weird and isn't committed to git. Secondly, git doesn't support symbolic links properly. Thirdly because it's a pain to create them in Windows. And I certainly don't want a symbolic link "somewhere else" for each markdown file I need to import, especially since it works fine without this preset.

**To Reproduce**

1. `npm i -D @storybook/preset-create-react-app`
2. Add to `addons` in `main.js`
3. Run Storybook

**Expected behavior**
Works. Nothing happens but a successful compilation.

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.190
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.45)
  npmPackages:
    @storybook/addon-a11y: 6.1.21 => 6.1.21
    @storybook/addon-actions: 6.1.21 => 6.1.21
    @storybook/addon-docs: 6.1.21 => 6.1.21
    @storybook/addon-knobs: 6.1.21 => 6.1.21
    @storybook/addons: ^6.1.21 => 6.1.21
    @storybook/preset-create-react-app: ^3.1.6 => 3.1.6
    @storybook/react: 6.1.21 => 6.1.21
    @storybook/theming: 6.1.21 => 6.1.21
```
(it still fails to find Firefox, not that it's relevant...)

Also I'd like to know what this preset actually does, except for just sort of being there, and presumably imposing arbitrary import rules. Why is it a warning to include this preset when SB works fine without it? What is it for, exactly?

And of course, how to fix this.

**Comment by shilman** [comment]
The CRA preset tries to replace Storybook's default react configuration (babel/webpack) with CRA's config. This used to be hard-coded inside `@storybook/react`, but putting it an addon both made it more modular AND came with a bunch of improvements.

As for how to solve your problem, I'm hoping @mrmckeb can help with that. This has come up a number of times and AFAIK there isn't an existing workaround.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
