### ISSUE TITLE
[5.2.0-beta.x] babel-loader error: Cannot find module core-js/modules/web.immediate.js and others

### ISSUE THREAD

**Issue by orangeloops** [storybookjs/storybook#7407]
After migration from 5.1.1 to 5.2.0-alpha.x (exactly the same config file) multiple babel-loader error arise.

Repo to reproduce (branch **storybook_5_2_0**): 
**https://github.com/orangeloops/public-ol-web-template/tree/storybook_5_2_0** 
npm install
npm run storybook

Modules:
es.symbol.iterator.js, es.symbol.js, es.symbol.to-string-tag.js, web.dom-collections.for-each.js

Error example:
ERROR in ./node_modules/@storybook/channels/dist/index.js
**Module not found: Error: Cannot find module '/Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/babel-loader/lib/index.js??ref--7-oneOf-6!/Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/core-js/modules/web.immediate.js'**
Require stack:
- /Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/corejs-upgrade-webpack-plugin/dist/index.js
- /Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js
- /Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/@storybook/core/dist/server/manager/manager-preset.js
- /Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/@storybook/core/dist/server/presets.js
- /Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/@storybook/core/dist/server/config.js
- /Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/@storybook/core/dist/server/build-static.js
- /Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/@storybook/core/server.js
- /Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/@storybook/react/dist/server/index.js
- /Users/daniel/Code/OrangeLoops/public-ol-web-template/node_modules/@storybook/react/bin/index.js
 @ ./node_modules/@storybook/channels/dist/index.js 35:0-40
 @ ./node_modules/@storybook/addons/dist/storybook-channel-mock.js
 @ ./node_modules/@storybook/addons/dist/public_api.js
 @ ./node_modules/@storybook/addon-knobs/dist/index.js
 @ ./.storybook/config.js

**Comment by Badlapje** [comment]
I have this exact same error when i clone the learn storybook repo and install this addon.

**Comment by orangeloops** [comment]
@norbert @shilman hi, how are you ?

did you have any chance to review this issue ? I can't migrate from 5.1.1 to any new version because of this issue.

@Badlapje mention that this issue also can be reproduced using "Learn Storybook" repo.

Thanks,
Daniel.

**Comment by ndelangen** [comment]
Thanks for the report:
https://github.com/orangeloops/public-ol-web-template/pull/17

Seems like `core-js` packages REALLY don't want to be transpiled by babel for some reason.

Make sure core-js is ignored if you're passing `node_modules` though babel (which isn't recommended for performance reason really.

**Comment by orangeloops** [comment]
@ndelangen 

Babel error was fixed 👍 , thank you!

BUT now I have "Rendered more hooks than during the previous render." with exactly the same basic story from 5.1.1

I did the merge on https://github.com/orangeloops/public-ol-web-template/tree/storybook_5_2_0

**Comment by ndelangen** [comment]
@Hypnosphi 2 months ago you added the error; and migrated addon-knobs to use the new hooks api.

What do you think might cause this behaviour?
https://github.com/orangeloops/public-ol-web-template/pull/17#issuecomment-513864171

<img width="1171" alt="Screenshot 2019-07-23 at 10 09 31" src="https://user-images.githubusercontent.com/3070389/61694773-78e8bf00-ad32-11e9-9177-0de6135d49a5.png">

**Comment by Hypnosphi** [comment]
Will take a look

**Comment by ndelangen** [comment]
Thanks for taking a look!

I looked at the @orangeloops code for how they create stories, but it a bit more complex then I could digest at a glance. I'm unsure if they use conditional knobs, but it could also be something async they do that causes this.

**Comment by Hypnosphi** [comment]
@ndelangen looks like the reason is `storybook-router` that exports a decorator which passes `storyFn` to a component instead of calling it synchronously:

https://github.com/gvaldambrini/storybook-router/blob/master/packages/react/react.js#L91-L97

**Comment by bennypowers** [comment]
This is relevant to #7084

**Comment by Hypnosphi** [comment]
Should be fixed with #8287
