### ISSUE TITLE
[Bug]: Proxy middleware stopped working after switching from Express to Polka in Storybook server

### ISSUE THREAD

**Issue by andreitsivm** [storybookjs/storybook#32073]
## Description

We used to run Storybook with a proxying our request with `http-proxy-middleware` in `middleware.js`. 
```js
export default function expressMiddleware(app) {
  app.use(
    ['/api', '/resources',],
    createProxyMiddleware({
      target: PROXY_HOST,
      changeOrigin: true,
      secure: false,
      timeout: 30000,
      cookieDomainRewrite: {
        [PROXY_FORWARDED_HOST]: 'localhost',
        localhost: PROXY_FORWARDED_HOST,
        '*': '',
      },
      /**
       * @see https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies
       * @param {Object} proxyRes
       */
      onProxyRes: proxyRes => {
        const sc = proxyRes.headers['set-cookie'];

        if (Array.isArray(sc)) {
          proxyRes.headers['set-cookie'] = sc.map(s =>
            s
              .split(';')
              .filter(v => v.trim().toLowerCase() !== 'secure')
              .join('; '),
          );
        }
      },
      onProxyReq: proxyReq => {
        proxyReq.setHeader('X-FORWARDED-HOST', PROXY_FORWARDED_HOST);
      },
    }),
  );
}
```

## What Changed

The only change was replacing Express with Polka for the custom server running Storybook. The same proxy middleware setup that worked with Express no longer works with Polka.

## Steps to Reproduce

Configure middleware with  `http-proxy-middleware`

## Expected Behavior

The proxy middleware should forward the request to the target backend.

## Actual Behavior
After update to v9 it stop to work with an error throwing
`TypeError: e.split is not a function`
## Environment

- Storybook version: 9.17
- Framework: React
- Builder: Webpack 5
- Node version: 22.15
- OS: macOS 15.5

## Additional Context

It seems that `http-proxy-middleware` depends on Express-style middleware chaining and request objects, which aren't fully compatible with Polka.

Is there a recommended way to restore proxy functionality in this setup?

Any help or suggestions would be greatly appreciated!

### Reproduction link

https://stackblitz.com/edit/github-cnfkxzft?file=.storybook%2Fmiddleware.js,package.json&preset=node

### Reproduction steps

npm run storybook

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 20.19.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm <----- active
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @storybook/addon-docs: ^9.1.0-alpha.3 => 9.1.0-alpha.8 
    @storybook/addon-onboarding: ^9.1.0-alpha.3 => 9.1.0-alpha.8 
    @storybook/preset-create-react-app: ^9.1.0-alpha.3 => 9.1.0-alpha.8 
    @storybook/react-webpack5: ^9.1.0-alpha.3 => 9.1.0-alpha.8 
    storybook: ^9.1.0-alpha.3 => 9.1.0-alpha.8
```
