### ISSUE TITLE
[Bug]: jsxDEV is not a function on production build with @storybook/react-vite 8.0.7

### ISSUE THREAD

**Issue by unional** [storybookjs/storybook#26919]
### Describe the bug

This only occurs during production build.

It works when build with `NODE_ENV=\"development\" storybook build`

### To Reproduce

I have a monorepo with multiple projects. One of them has this issue while other doesn't.

So haven't find a way to repro it yet.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.0.4 - ~/.nvm/versions/node/v20.12.2/bin/pnpm <----- active
  Browsers:
    Chrome: 124.0.6367.62
    Safari: 17.4.1
```

**Comment by rejas** [comment]
We encountered this bug also when upgrading vom v7 to v8 in our monorepo. Afterwards our seperate app failed the production build when using our monorepo libraries...

**Comment by juandinella** [comment]
Any update on this? @unional @rejas ?

**Comment by unional** [comment]
I have not have the time to look into it. I'm using the dev build as a workaround.

Also, try adding `esbuild: { jsx: 'automatic' }` to your `vite.config.ts` and see if that helps

**Comment by rejas** [comment]
We "fixed" it by updating sb to v8 manually and not by using the nx migration process I was told. Plus we deactivated pnpm caching in our nx/github ci setup for this.

**Comment by juandinella** [comment]
I fixed doing `"build": "NODE_ENV=production VITE_USER_NODE_ENV=production vite build --mode production",`
