### ISSUE TITLE
[6.2.0 alpha] Webpack 5 related issues

### ISSUE THREAD

**Issue by phaistonian** [storybookjs/storybook#14005]
Here are a couple of issues I noticed after trying the latest alpha `6.2.0-alpha.34`.

- [ ] [react-refresh](https://github.com/pmmmwh/react-refresh-webpack-plugin) won't work. More context [here](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/308#issuecomment-776612653)
- [ ] Both [postcss-loader](https://github.com/webpack-contrib/postcss-loader/releases/tag/v5.0.0) and [stylus-loader](https://github.com/webpack-contrib/postcss-loader/releases/tag/v5.0.0) won't work in version `5.0.0`.

Both those issues seem to be related to confusion in terms of the _active_ webpack version.

Ps: tried to force set the version to `4` in `react-refresh` and more errors came up.

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by phaistonian** [comment]
@shilman Nope — it was tested directly in our product (in a branch). I could share the custom webpack config we use, but I believe it would cause more confusion than help.

**Comment by shilman** [comment]
Can you clarify the postcss/stylus comment? I believe I used postcss successfully in a test webpack5 project using `@storybook/addon-postcss`

**Comment by phaistonian** [comment]
Both those loaders have as a minimum required for Webpak to be `5.x`.

Here's the error:

```
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
```
from
```js
async function loader(content, sourceMap, meta) {
  const options = this.getOptions(_options.default);
```

**Comment by phated** [comment]
@shilman how should we handle the postcss-loader issue? I'd say that consumers of webpack 5 + postcss should **have** to install our new `addon-postcss`.

**Comment by shilman** [comment]
@phated yeah i got this boilerplate working with webpack5 and `addon-postcss`: https://github.com/altafino/react-webpack-5-tailwind-2

**Comment by jsg2021** [comment]
I'm using postcss-loader@5 and webpack@5 just fine in my regular dev env. Is there something special with storybook?

**Comment by shilman** [comment]
@jsg2021 storybook has been based on webpack4 until recently when we've added the option to use webpack5

**Comment by jsg2021** [comment]
> @jsg2021 storybook has been based on webpack4 until recently when we've added the option to use webpack5

@shilman is there docs for this option? any caveats?

**Comment by shilman** [comment]
it's experimental. here are the WIP docs

https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324

**Comment by phaistonian** [comment]
Closing this issue since the latest betas have resolved those issues.

Ps: great work @shilman and all!
