### PR TITLE
Core: Fix addon bundling script

### LINKED ISSUE #26: Error: Cannot find module '@storybook/global'
Hi, I tried to integrate your addon using the context described below:
- Storybook 7.6.3 (also tried using 7.5)
- Angular 16.2.10

But when I start Storybook I got the following error using Firefox: 

```
Error: Cannot find module '@storybook/global'
    webpackEmptyContext sync:2
    js index.js:23
    Angular 2
    Webpack 25
[runtime.js:4:101929](http://localhost:6006/sb-preview/runtime.js)
    error runtime.js:4
    renderPreviewEntryError runtime.js:89
    renderPreviewEntryError runtime.js:103
    getProjectAnnotationsOrRenderError runtime.js:87
    _runRejections runtime.js:4
    _runRejections runtime.js:4
    catch runtime.js:4
    getProjectAnnotationsOrRenderError runtime.js:87
    initialize runtime.js:81
    js storybook-config-entry.js:25
```

Same error but using Chrome which provides a more explicit stack-trace:

```
   runtime.js:4 Error: Cannot find module '@storybook/global'
    at webpackEmptyContext ( sync:2:1)
    at ../../lib/channels/dist/index.js (index.js:23:1)
    at index.js:8:1
    at ./node_modules/@storybook/addon-actions/dist/index.js (index.js:23:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/storybook-addon-angular-router/dist/actionLoggingRouter.js (actionLoggingRouter.js:7:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/storybook-addon-angular-router/dist/withAngularRouter.js (withAngularRouter.js:10:1
```

    
To reproduce:

1. `npx @angular/cli@16.2 new mylib --no-create-application`
2. `cd mylib/`
3. `npx @angular/cli@16.2 generate library my-lib`
4. `npx storybook@latest init`
5. `npm i -D storybook-addon-angular-router`
6. Add the storybook-addon-angular-router addon in `/mylib/projects/my-lib/.storybook/main.ts`
7. `ng run my-lib:storybook`
8. Access http://localhost:6006/
9. F12 to show JS console and check the error

### LINKED ISSUE #26030: [Bug]: Cannot find module '@storybook/global'
### Describe the bug

Suddenly after reinstalling my node_modules i cannot start my storybook dev server again.
I'm not sure whether this is related to: https://github.com/storybookjs/storybook/issues/25130

```
Error: Cannot find module '@storybook/global'
    at webpackEmptyContext (http://localhost:4400/main.iframe.bundle.js:606:10)
    at ../../lib/channels/dist/index.js (http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-9ff264.iframe.bundle.js:104060:26)
    at http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-9ff264.iframe.bundle.js:100320:50
    at ./node_modules/@storybook/addon-actions/dist/index.js (http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-9ff264.iframe.bundle.js:104410:31)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:338:21)
    at ./node_modules/storybook-addon-angular-router/dist/actionLoggingRouter.js (http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-9ff264.iframe.bundle.js:142568:21)
    at __webpack_require__ (http://localhost:4400/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:4400/runtime~main.iframe.bundle.js:338:21)
    at ./node_modules/storybook-addon-angular-router/dist/withAngularRouter.js (http://localhost:4400/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-9ff264.iframe.bundle.js:142777:28)
```

I'm Using angular in an nx monorepo and created a custom ui library with a storybook installation.

```
/my-monorepo
├── apps
└── libs
    └── my-ui
        ├── .storybook
        │   ├── main.ts
        │   ├── preview.ts
        │   ├── theme.ts
        │   ├── manager.ts
        │   └── tsconfig.json
        └── components
            └── ...
```

This is an excerpt of my package json:
```
{
    "devDependencies": {
        ...
        "@angular/cli": "~17.1.0",
        "@nx/angular": "17.3.2",
        "@nx/storybook": "17.3.2",
        "@storybook/addon-links": "^7.6.3",
        "@storybook/addon-essentials": "7.6.14",
        "@storybook/angular": "7.6.14",
        "@storybook/core-server": "7.6.14", 
        ...
    }
}
```

### To Reproduce

_No response_

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.4.0 - ~/.nvm/versions/node/v18.19.0/bin/npm <----- active
    pnpm: 8.15.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 121.0.6167.160
    Safari: 17.3.1
  npmPackages:
    @storybook/addon-essentials: ^7.6.15 => 7.6.15 
    @storybook/addon-links: ^7.6.15 => 7.6.15 
    @storybook/angular: ^7.6.15 => 7.6.15 
    @storybook/core-server: ^7.6.15 => 7.6.15 
    eslint-plugin-storybook: ^0.6.11 => 0.6.15 
    storybook-addon-angular-router: ^1.9.2 => 1.9.2
```

### Additional context

_No response_

### LINKED ISSUE #26126: [Bug]: Error `Cannot find module @storybook/global` is thrown when Babel is used with CommonJS modules in 7.6+
### Describe the bug

When Webpack & Babel are used, and `@babel/preset-env` is configured with `modules: 'commonjs'`, a runtime error is thrown when viewing stories that import `action` from `@storybook/addon-actions`.

This worked in 7.5.3, and is a regression starting from 7.6.

Screenshot 2024-02-20 at 1 15 34 PM

To be honest, I'm not positive that this is a bug in Storybook. My gut feeling is that the best solution could be to ask users to fix their Babel configs to use `modules: 'auto'` as recommended [in their docs](https://babeljs.io/docs/babel-preset-env#modules), but in that case it should be added to the migration notes as it represents a BC break from 7.5.

### To Reproduce

* Repo: https://github.com/soren121/storybook-addons-bug-repro
* StackBlitz demo: https://stackblitz.com/github/soren121/storybook-addons-bug-repro

Navigate to the Button example in Storybook, and a runtime error should be thrown.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 13.6.4
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn <----- active
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 7.5.2 - ~/.asdf/shims/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.3.1
  npmPackages:
    @storybook/addon-essentials: ^7.6.16 => 7.6.17 
    @storybook/addon-interactions: ^7.6.16 => 7.6.17 
    @storybook/addon-links: ^7.6.16 => 7.6.17 
    @storybook/addon-onboarding: ^1.0.11 => 1.0.11 
    @storybook/blocks: ^7.6.16 => 7.6.17 
    @storybook/react: ^7.6.16 => 7.6.17 
    @storybook/react-webpack5: ^7.6.16 => 7.6.17 
    @storybook/test: ^7.6.16 => 7.6.17 
    storybook: ^7.6.16 => 7.6.17
```

### Additional context

A similar bug was tracked in #25130, but it appears there is more than one cause, as others still report issues after a fix was identified.

### PR DESCRIPTION
**Pull request by ndelangen**
Closes: https://github.com/storybookjs/storybook/issues/26126
Closes: https://github.com/Jakob-em/storybook-addon-angular-router/issues/26
Closes: https://github.com/storybookjs/storybook/issues/26030

## What I did

I researched the problem and discovered:
- this is only a problem when using webpack
- our `addons/actions/dist/index.js` (which is an export-type-entry for the addon is compiled in ESM and CJS, however the CJS is compiled for NODE.
- our `addons/actions/dist/index.js` (which is an import-type-entry for the addon is compiled in ESM and CJS, however the CJS is compiling in all preview related packages (package consolidation would fix this).
- The user's config is compiling stories to CJS, which then causes the CJS version of the export-type-entry to be chosen by webpack.

These factors cause code designed to be run in NODE (unbundled), to be bundled again and then ran in a browser.

It seems webpack just can't really work with the output from esbuild when esbuild compiled for NODE, and webpack compiles for the browser. It creates an empty context, which then causes the issue.

## How I fixed it:

I changed the bundling script that bundles our addons, so that it now does:
- always externalizes all the storybook packages, including `preview-api`.
- it compiles for a platform of `neutral`.
- it choses whatever entry it deems best, no longer forcing it to use `module`.

The result is that:
- 7.x repro works with this change applied
- after upgrading the 7.x repro to sb8 beta, and applying this fix, it works
- The dist output of `addons/actions/dist/index.js` has 7800 lines of code removed.

## What is next?

I am pretty confident in this change, however it does change the dynamics with NODE.

I'd like to ask @yannbf 's help to verify if this did not change/break  portable stories or the test-runner in some way.

I'd also like @shilman 's position on how safe they feel this change is.

This change would need to be patched back to 7.x.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

I published a canary, so testing this with any sandbox or repro should be easy.

Check if:
- upgrade works, storybook starts
- if all expected addon panels show up
- if addon-a11y functionality works
- if addon-actions functionality

Also check:
- does the test-runner still works.
- does portable stories work as expected

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This pull request has been released as version `0.0.0-pr-26145-sha-32b8346f`. Try it out in a new sandbox by running `npx storybook@0.0.0-pr-26145-sha-32b8346f sandbox` or in an existing project with `npx storybook@0.0.0-pr-26145-sha-32b8346f upgrade`.
<details>
<summary>More information</summary>

| | |
| --- | --- |
| **Published version** | [`0.0.0-pr-26145-sha-32b8346f`](https://npmjs.com/package/@storybook/cli/v/0.0.0-pr-26145-sha-32b8346f) |
| **Triggered by** | @ndelangen |
| **Repository** | [storybookjs/storybook](https://github.com/storybookjs/storybook) |
| **Branch** | [`norbert/fix-addon-bundling`](https://github.com/storybookjs/storybook/tree/norbert/fix-addon-bundling) |
| **Commit** | [`32b8346f`](https://github.com/storybookjs/storybook/commit/32b8346fc2be9e3b9130ed9999b0450ec1e3e441) |
| **Datetime** | Thu Feb 22 12:30:52 UTC 2024 (`1708605052`) |
| **Workflow run** | [8004494946](https://github.com/storybookjs/storybook/actions/runs/8004494946) |

To request a new release of this pull request, mention the `@storybookjs/core` team.

_core team members can create a new canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=26145`_
</details>

### CODE REVIEW

File: scripts/prepare/addon-bundle.ts [hunk 1]
```diff
@@ -120,13 +120,12 @@ const run = async ({ cwd, flags }: { cwd: string; flags: string[] }) => {
         ...(optimized ? dtsConfig : {}),
         entry: exportEntries,
         format: ['cjs'],
-        target: 'node18',
-        platform: 'node',
-        external: commonExternals,
+        target: 'chrome100',
```
Comment (JReinhold) [inline scripts/prepare/addon-bundle.ts:123]: Would it make sense to use the same targets as our browser modules?

```suggestion
        target: browserOptions.target,
```

**Comment by yannbf** [comment]
I used the canary to test portable stories and although I found issues, these issues are unrelated to this PR, so from the perspective of portable-stories I think the changes look good 👍

**Review by yannbf — APPROVED** [review]
LGTM I Think!

**Review by shilman — APPROVED** [review]
I'm not confident about patching this back. But let's get it out in 8.0-beta ASAP and see how it does there. Great job!!! ❤️

**Comment by AndyOGo** [comment]
Will this land in v7 any time soon?

**Comment by yannbf** [comment]
> Will this land in v7 any time soon?

This is included in 7.6.18 and 8.0.0

**Comment by AndyOGo** [comment]
@yannbf 
Am I looking at the wrong version?

> This is included in 7.6.18 and 8.0.0

https://www.npmjs.com/package/storybook/v/7.6.18
Screenshot 2024-03-26 at 19 08 16

**Comment by AndyOGo** [comment]
@ndelangen 
@yannbf 
@shilman 
@JReinhold 

> This is included in **7.6.18** and 8.0.0

Which package please?

These aren't published as `v7.6.18`
- https://www.npmjs.com/package/storybook/v/7.6.18
- https://www.npmjs.com/package/@storybook/addon-actions/v/7.6.18

**Comment by shilman** [comment]
@AndyOGo It doesn't look like 7.6.18 has been published. Are you unable to upgrade to Storybook 8?

**Comment by AndyOGo** [comment]
@shilman Thx for your answer.
Yes, we can't upgrade to v8 at the moment.

**Comment by sjwilczynski** [comment]
For us, it is also a problem. Would really appreciate if it could be ported back to v7

**Comment by reshu0408** [comment]
@shilman Its causing a problem for us too. and blocking an important release. Can you please work to get the patch in V7 version. Please. I would be very thankful.

**Comment by yannbf** [comment]
@ndelangen seems like the patch release that was going to include this change was closed, I'm not sure why: https://github.com/storybookjs/storybook/pull/26121

**Comment by heathercodes** [comment]
+1 when will this be released in 7.6.18? we can't jump all the way to v8 yet, we need a working v7 first.

**Comment by AndyOGo** [comment]
@ndelangen Please respond

**Comment by JReinhold** [comment]
@AndyOGo, @heathercodes, @sjwilczynski, @reshu0408 v7.6.18 has been released now with the fix.

https://github.com/storybookjs/storybook/releases/tag/v7.6.18
