### ISSUE TITLE
BREAKING CHANGE detected `@storybook/addon-interactions@8.2.0` removes `@storybook/test` module

### ISSUE THREAD

**Issue by valentinpalkovic** [storybookjs/storybook#28517]
### Discussed in https://github.com/storybookjs/storybook/discussions/28516

<div type='discussions-op-text'>

<sup>Originally posted by **valpioner** July 10, 2024</sup>
### Summary

Updating storybook to 8.2.0 broke our project.

Context:
We use `import { fn } from '@storybook/test';`
After we updated to 8.2.0, this module is not there any more.
After additional investigation, looks like `@storybook/addon-interactions@8.2.0` is responsible for that.

TS Error:
`Cannot find module '@storybook/test' or its corresponding type declarations.ts(2307)`

<img width="927" alt="image" src="https://github.com/storybookjs/storybook/assets/12964569/2e7e8162-03e5-4529-9296-50e2c07b2898">

### Create a reproduction

_No response_</div>

**Comment by giacoder** [comment]
For those who still have this issue:
instead of 
```import { fn } from "@storybook/test";```
type
```import { fn } from "storybook/test";```

(without @)
