### ISSUE TITLE
StoryDecorator and RenderFunction need to be exported.

### ISSUE THREAD

**Issue by rakeshpai** [storybookjs/storybook#8160]
Migrating to 5.2.x has caused build errors in my TS project:
```
node_modules/@types/storybook__addon-info/index.d.ts:10:10 - error TS2305: Module '"path/to/project/node_modules/@storybook/react/dist/client"' has no exported member 'RenderFunction'.

10 import { RenderFunction, StoryDecorator } from '@storybook/react';
            ~~~~~~~~~~~~~~

node_modules/@types/storybook__addon-info/index.d.ts:10:26 - error TS2305: Module '"path/to/project/node_modules/@storybook/react/dist/client"' has no exported member 'StoryDecorator'.

10 import { RenderFunction, StoryDecorator } from '@storybook/react';
                            ~~~~~~~~~~~~~~

node_modules/@types/storybook__addon-knobs/index.d.ts:13:10 - error TS2305: Module '"path/to/project/node_modules/@storybook/react/dist/client"' has no exported member 'RenderFunction'.

13 import { RenderFunction } from '@storybook/react';
            ~~~~~~~~~~~~~~

node_modules/@types/storybook__addon-viewport/index.d.ts:7:10 - error TS2305: Module '"path/to/project/node_modules/@storybook/react/dist/client"' has no exported member 'StoryDecorator'.

7 import { StoryDecorator } from '@storybook/react';
           ~~~~~~~~~~~~~~
```

It looks like `StoryDecorator` and `RenderFunction` need to be exported from `@storybook/react`.

**Expected behavior**
Addons with TS should Just Work.

**Comment by rakeshpai** [comment]
Possibly related: https://github.com/storybookjs/storybook/pull/8121

**Comment by ndelangen** [comment]
You were using https://www.npmjs.com/package/@types/storybook__react before?

You should now get types without it, so there should be no need to import RenderFunction or StoryDecorator anymore.

**Comment by rakeshpai** [comment]
I was, but I've removed `@types/storybook__react` now. It looks like these errors aren't from my code though. It seems to be originating from the addons. So I'm not sure if this is anything I can do to fix, but I'll be happy to stand corrected.

**Comment by ndelangen** [comment]
Please remove `@types/storybook__addon-info` too, it's types will be incorrect.

I'd recommend migrating to the docs addon, which has types!

**Comment by rakeshpai** [comment]
Thanks, @ndelangen. I tried removing `@types/storybook__addon-info`, but its package.json doesn't have a `types` field, so its types aren't picked up automatically. https://unpkg.com/@storybook/addon-ionfo@5.2.1/package.json This is also true of the viewport addon. https://unpkg.com/@storybook/addon-viewport@5.2.1/package.json

Migrating to the docs addon is on the cards (it looks awesome!), but I was hoping to keep things working as I'm migrating.

**Comment by ndelangen** [comment]
@rakeshpai The viewport addon doesn't need any types. It's a register only addon.

Previously users would import a `withViewport`, but this has been deprecated.

The addon info is unofficially deprecated. We will not add types to it.
I recommend you silence the build error using some custom typescript code or `any`.

You could also take ownership of the `@types/storybook__addon-info` package and fix it, if you'd like. or use it as a starter to create a locally defined types for the package.

**Comment by rakeshpai** [comment]
Hi @ndelangen 

This error is from inside the addons, not from my usage of them. The addons are complaining that @storybook/react isn't exporting the correct things.

```
node_modules/@types/storybook__addon-knobs/index.d.ts:13:10 - error TS2305: Module '"path/to/project/node_modules/@storybook/react/dist/client"' has no exported member 'RenderFunction'.

13 import { RenderFunction } from '@storybook/react';
            ~~~~~~~~~~~~~~

node_modules/@types/storybook__addon-viewport/index.d.ts:7:10 - error TS2305: Module '"path/to/project/node_modules/@storybook/react/dist/client"' has no exported member 'StoryDecorator'.

7 import { StoryDecorator } from '@storybook/react';
           ~~~~~~~~~~~~~~
```

In other words, this is complaining that `RenderFunction` and `StoryDecorator` isn't available here: https://unpkg.com/@storybook/react@5.2.1/dist/client/index.d.ts These imports aren't in my code, they are in the addons.

**Comment by rakeshpai** [comment]
Sorry, deleted my last comment, it was incorrect. I'll update this thread with my latest findings.

**Comment by shilman** [comment]
@rakeshpai we'll try to resolve the addon-docs typescript support soon in 5.3! you should also just be able to disable source code in docs for now as a workaround?

**Comment by good-idea** [comment]
@rakeshpai , I'm able to get this to work in 5.2 if my storybook config file is `.js`
