### ISSUE TITLE
Cannot find module 'react-dom/client' in render.jss under React 18

### ISSUE THREAD

**Issue by dontsave** [storybookjs/storybook#18402]
**Describe the bug**
render.jss is erroring after upgrading to React 18 when attempting to access `react-dom/client`

**To Reproduce**
Run storybook with React 18.1.0

**System**
```
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - ~/frame.io/web-app/node_modules/.bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.1
  npmPackages:
    @storybook/addon-actions: 6.3.7 => 6.3.7 
    @storybook/addon-knobs: 6.3.0 => 6.3.0 

```

**Comment by GuyGooL5** [comment]
I'm facing the same problem after upgrading to 6.5.6. I'm using storybook for react 17 with builder-vite.
Node version: v14.17.5
NPM version: 8.3.0

dependencies:
```
    "react": "^17.0.2",
    "react-dom": "^17.0.2",

```

devDependencies :
```
    "@storybook/addon-actions": "^6.5.6",
    "@storybook/addon-essentials": "^6.5.6",
    "@storybook/addon-links": "^6.5.6",
    "@storybook/api": "^6.5.6",
    "@storybook/builder-vite": "^0.1.36",
    "@storybook/react": "^6.5.6"
    "vite": "^2.7.2"
    ...

```

**Comment by GuyGooL5** [comment]
@grimor actually what solved it for me was changing `"react-dom/client"` to `"react-dom"`

**Comment by grimor** [comment]
@GuyGooL5 Cool, I've also found out that my webpack config overrides was overwriting `IgnorePlugin` used in storybook which tells webpack to ignore `react-dom/client`. When I've included that into my webpack config it build correctly without patching `render.js` file.

**Comment by thibaudcolas** [comment]
I’m facing the same issue as well in Storybook v6.5, with React 16, and no particular Webpack overrides that seem relevant to this.

This seems like a clear-cut bug to me – the Storybook rendering logic attempts to conditionally load `react-dom/client`, but at build time there’s no way for Webpack to tell that the import is conditional. So it’ll still attempt to resolve this no matter what:

https://github.com/storybookjs/storybook/blob/e2673f765722cbb542ef1b5cf8d533c8e746a127/app/react/src/client/preview/render.tsx#L76

**Comment by thibaudcolas** [comment]
I’ve managed to reproduce the issue, and opened it separately at #18662 because it seems different to what everyone else is reporting here. I think my issue affects React 16 and 17 but clearly shouldn’t be a problem for React 18 users.

**Comment by BeeeQueue** [comment]
Can confirm this happening to us using React 17 and Storybook 6.5

Quick workaround that works for me is to mark `react-dom/client` as external in Storybook's Webpack config

```js
// main.js
module.exports = {
  webpackFinal: (config) => {
    // Storybook 6.5 added support for React 18's new Root API, but fails to realize we
    // arent using React 18 yet, so it fails when it can't find it.
    // https://github.com/storybookjs/storybook/issues/18402
    config.externals = ["react-dom/client"]
  }
}
```

**Comment by SpookyJelly** [comment]
having same issue. Using sb for react 17 with vite.

```json
// package.json
  "dependencies": {
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },

"devDependencies":{
    "@storybook/react": "^6.5.15",

}
```

I can fix this erase all plugin with problems on storybook's `main.ts`. but It doesn't seem a total solution. 
Really no clue why `react-dom/client` appears in this context. Hope somebody solved this already

**Comment by vgoreev** [comment]
Just in case someone encountering the same issue with the latest Storybook packages combined with React 17. 

We've got React 17 in our project but @storybook requires React 18 for its manager plugin. So I came up with this workaround. So essentially Storybook uses a package called @storybook/react-dom-shim to create a unified way of mounting and unmounting components. We need to explicitly tell storybook's webpack to use react-16 version of a shim. Here is a code that worked for me. 

```ts
// main.ts
     ...
     
    webpackFinal(config) {
        config.resolve = {
            extensions: ['.ts', '.tsx', '.js', '.jsx'],
            alias: {
                react: getAbsolutePath('react'),
                'react-dom': getAbsolutePath('react-dom'),
                '@storybook/react-dom-shim': '@storybook/react-dom-shim/dist/react-16',
            },
        };

        return config;
    },
    ```

**Comment by valentinpalkovic** [comment]
This was specific to Storybook 6.3's `framework-preset-react-dom-hack.js` and React 18 transition. React 18+ is now required and `@storybook/react-vite`/`@storybook/react-webpack5` use `react-dom/client` unconditionally; the hack preset was removed. Closing as obsolete.
