### ISSUE TITLE
Angular: ngModel/ngModelChange don't work in Storybook 6.2+

### ISSUE THREAD

**Issue by vetrov** [storybookjs/storybook#14643]
**What's the problem?**
There was a way to define inputs for Angular components implementing ControlValueAccessor interface (reactive form controls) by using `ngModel` and `ngModelChange` as props in story. After upgrading to Storybook 6.2 these props seems do not work anymore.

* new renderer: nothing happens, component.writeValue is not called
* old renderer (angularLegacyRendering: true): see this error in console: `TypeError: instance.writeValue is not a function`, value is not passed to the component

**Example:**

Story for this use case exists in the demo, but does not work as well: https://next--storybookjs.netlify.app/angular-cli/?path=/story/basics-angular-forms-controlvalueaccessor--simple-input (currently works on Storybook 6.3.0-alpha.9)

Code for this story: https://github.com/storybookjs/storybook/blob/v6.3.0-alpha.9/examples/angular-cli/src/stories/basics/angular-forms/customControlValueAccessor/custom-cva-component.stories.ts

**Is there documentation on this?**
`ngModel` and `ngModelChange` are not mentioned in documentation, so it's more like undocumented (but implemented) feature.

Here is more details on how it is implemented in old renderer: https://github.com/storybookjs/storybook/blob/v6.2.8/app/angular/src/client/preview/angular/components/app.component.ts#L110

**Additional context**
Would be good to understand if it's a bug or there's now another way to create stories for Angular form controls.

**Comment by daan93** [comment]
I can confirm this issue on storybook 11.2.11. In my console the following error shows up. 

![image](https://user-images.githubusercontent.com/7119213/115864200-d8f42400-a436-11eb-839c-478f1b347d30.png)

**Comment by vetrov** [comment]
> I can confirm this issue on storybook 11.2.9. In my console the following error shows up.

@daan93 Looks like you need to explicitly import FormsModule into your story. Do you have something like this in your code?
```
export default {
     title: 'Components/My Component,
     component: AdsColorInputComponent,
    decorators: [
        moduleMetadata({
            imports: [
                FormsModule
            ]
        })
    ]
};
```

**Comment by shilman** [comment]
@ThibaudAV any idea what's changed? ☝️

**Comment by ThibaudAV** [comment]
🤔 arf, Bad behaviors of previous version which gives bad habits, I think 😁. The FormsModule was always loaded by storybook probably for some obscure reason.

As the new renderer behaves like a real angular application in this case if. So there are the same errors as if you have an angular application without this import 
FormsModule is an implementation detail. Not all stories need it, so it comes back to each story needing to "add it"
I also think, the peerDependencies on `@angular/forms` should be deleted in apps/angular (with sb v7 ?)


the error message of angular is ~clear. But maybe a precision can be brought in the MIGRATION.md or the answer to this issue is enough 🤷‍♂️

**Comment by vetrov** [comment]
@ThibaudAV how about the original question, have you noticed this issue with Storybook 6.2+?

**Comment by ThibaudAV** [comment]
@vetrov Could you provide an example where it does not work from this [story](https://github.com/storybookjs/storybook/blob/v6.3.0-alpha.9/examples/angular-cli/src/stories/basics/angular-forms/customControlValueAccessor/custom-cva-component.stories.ts) 🙏  ? 

The new renderer generates a "template" so if the component is placed in the same condition (import, dep,...) as an angular application. there should be no difference 🤔 
So all that is ngModel and ngModelChange and life cycle of a component is done by angular and not by storybook

**Comment by vetrov** [comment]
@ThibaudAV, sure, here is how to reproduce what I'm doing:

Open Storybook example for Angular form control: [open story](https://next--storybookjs.netlify.app/angular-cli/?path=/story/basics-angular-forms-controlvalueaccessor--simple-input ). It is based on v6.3.0-alpha.16 as I can see from _About_.

As I understood this is a source code for the example above: [source code](https://github.com/storybookjs/storybook/blob/v6.3.0-alpha.16/examples/angular-cli/src/stories/basics/angular-forms/customControlValueAccessor/custom-cva-component.stories.ts)

Looking on source code I expect, that:
* Input is prefilled with "Type anything" when open story, but it's empty
* When I'm typing something in the input, action is logged in Actions tab, but it is not

Same behaviour I observe when running the same example story for Storybook 6.2.9

**Comment by shilman** [comment]
Please try upgrading to the latest prerelease. Is it still a problem?

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by simon-fryer1** [comment]
Hi, any update on this? I've upgraded to version 7 of Storybook and it's still an issue. It appears after looking at the new code that the ngModel and ngChnageModel values are not set any longer.

**Comment by Kondziowsky** [comment]
Hello, same problem here, any updates how to fix this updating ngModel? I feel like storybook 7.4 + angular 15 is a little messy in few points.
