### ISSUE TITLE
[Bug]: Cannot find name 'PromiseWithResolvers' 

### ISSUE THREAD

**Issue by jlowcs** [storybookjs/storybook#28527]
### Describe the bug

A [reference](https://github.com/storybookjs/storybook/blob/9678d6f3774f3d4e0dcdc19bbf20735d670e7550/code/core/src/preview-api/modules/store/csf/portable-stories.ts#L265) to `PromiseWithResolvers` was introduced by https://github.com/storybookjs/storybook/pull/28383

That type is not imported anywhere in that file and my library (using react) doesn't compile because of it.

### Reproduction link

N/A

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm <----- active
  Browsers:
    Chrome: 126.0.6478.127
    Firefox: 128.0
    Safari: 17.5
  npmPackages:
    @storybook/addon-a11y: ^8.2.1 => 8.2.1 
    @storybook/addon-actions: ^8.2.1 => 8.2.1 
    @storybook/addon-docs: ^8.2.1 => 8.2.1 
    @storybook/addon-essentials: ^8.2.1 => 8.2.1 
    @storybook/addon-interactions: ^8.2.1 => 8.2.1 
    @storybook/addon-links: ^8.2.1 => 8.2.1 
    @storybook/addon-webpack5-compiler-swc: ^1.0.4 => 1.0.4 
    @storybook/cli: ^8.2.1 => 8.2.1 
    @storybook/components: ^8.2.1 => 8.2.1 
    @storybook/manager-api: ^8.2.1 => 8.2.1 
    @storybook/node-logger: ^8.2.1 => 8.2.1 
    @storybook/react: ^8.2.1 => 8.2.1 
    @storybook/react-webpack5: ^8.2.1 => 8.2.1 
    @storybook/testing-library: ^0.2.2 => 0.2.2 
    @storybook/theming: ^8.2.1 => 8.2.1 
    storybook: ^8.1.11 => 8.2.1
```

**Comment by valpioner** [comment]
Having the same issue with 8.2.1 during a regular build for our angular library (ng run my-project:storybook)
TS2304: Cannot find name 'PromiseWithResolvers'.

Node version: v20.15.0 
TypeScript 5.4.5


![image](https://github.com/storybookjs/storybook/assets/12964569/e5719039-9eaa-4c8e-8dda-15073570e044)
![image](https://github.com/storybookjs/storybook/assets/12964569/c7444ad1-f697-45f0-a915-c21bf5316ae7)

**Comment by bertheto** [comment]
Hello I have the same issue on my side with the 8.2.1...
```
node_modules/@storybook/core/dist/preview-api/index.d.ts:349:22 - error TS2304: Cannot find name 'PromiseWithResolvers'.

349     renderingEnded?: PromiseWithResolvers<void>;
                         ~~~~~~~~~~~~~~~~~~~~

=> Failed to build the preview
SB_BUILDER-WEBPACK5_0003 (WebpackCompilationError): There were problems when compiling your code with Webpack.
Run Storybook with --debug-webpack for more information.

```

**Comment by bertheto** [comment]
Even if I come back to the 8.1.11 Story book version, it is still the v8.2.x @storybook/preview-api version wich is installed by NPM ... and in my node module, there is no dist folder regarding this version.

**Comment by bertheto** [comment]
> @kasperpeulen is working on a fix. We will try to release a hotfix soon!

Great ! thank you in advance !

**Comment by matijs** [comment]
Adding `"ESNext"` to `"lib"` in `tsconfig.json` works but I'm not sure that's feasible for everyone.
