### ISSUE TITLE
Storybook v6 + vue + tsx -> tsc errors: conflict types with @types/react

### ISSUE THREAD

**Issue by voskresla** [storybookjs/storybook#12505]
**Describe the bug**
After migration from 5.2 to 6 `npx tsc` throw errors: 
- `Property 'class' does not exist on type 'DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>'`
- `Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<...>, Record<...>>'.`

**To Reproduce**

1. Clone 'https://github.com/voskresla/sb-migrate-reproduce'
2. Run 'npm i && npx tsc'

**Expected behavior**
No errors )

**Screenshots**

**Code snippets**

**System:**
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-knobs: ^6.0.21 => 6.0.21 
    @storybook/source-loader: ^6.0.21 => 6.0.21 
    @storybook/vue: ^6.0.21 => 6.0.21 

**Additional context**
Package `@types/react` came as deps for `@types/react-color` and `@types/react-syntax-highlighter`

If delete types `rm -rf ./node_modules/@types/react`, everything works like a charm.

Or i can use `path` in `tsconfig` to solve this. 
```
compilerOptions.path = {
      "react": ["./nothins.d.ts"],
}
```

**Comment by ProTip** [comment]
Seeing the same in `5.3.19`. Those should probably be listed as dev dependencies?

**Comment by YuJianghao** [comment]
Is this the same problem?

Seems `@vue/runtime-dom` has conflicts with `@types/react`

error outputs:
```
node_modules/@types/react/index.d.ts:120:51 - error TS2344: Type 'C' does not satisfy the constraint 'ElementType<any>'.
  Type 'keyof IntrinsicElements | ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) | ((props: any, context?: any) => ReactElement<...> | null)' is not assignable to type 'ElementType<any>'.
    Type 'number' is not assignable to type 'ElementType<any>'.
      Type 'C' is not assignable to type 'FunctionComponent<any>'.
        Type 'keyof IntrinsicElements | ForwardRefExoticComponent<any> | (new (props: any) => Component<any, {}, any>) | ((props: any, context?: any) => ReactElement<...> | null)' is not assignable to type 'FunctionComponent<any>'.
          Type 'string' is not assignable to type 'FunctionComponent<any>'.

120         "ref" extends keyof ComponentPropsWithRef<C>
                                                      ~

node_modules/@types/react/index.d.ts:121:49 - error TS2344: Type 'C' does not satisfy the constraint 'ElementType<any>'.
  Type 'C' is not assignable to type 'FunctionComponent<any>'.

121             ? NonNullable<ComponentPropsWithRef<C>["ref"]> extends Ref<
                                                    ~

node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:1493:15 - error TS2320: Interface 'Element' cannot simultaneously extend types 'VNode<RendererNode, RendererElement, { [key: string]: any; }>' and 'ReactElement<any, any>'.
  Named property 'key' of types 'VNode<RendererNode, RendererElement, { [key: string]: any; }>' and 'ReactElement<any, any>' are not identical.

1493     interface Element extends VNode {}
                   ~~~~~~~

node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:1493:15 - error TS2320: Interface 'Element' cannot simultaneously extend types 'VNode<RendererNode, RendererElement, { [key: string]: any; }>' and 'ReactElement<any, any>'.
  Named property 'props' of types 'VNode<RendererNode, RendererElement, { [key: string]: any; }>' and 'ReactElement<any, any>' are not identical.

1493     interface Element extends VNode {}
                   ~~~~~~~

node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:1493:15 - error TS2320: Interface 'Element' cannot simultaneously extend types 'VNode<RendererNode, RendererElement, { [key: string]: any; }>' and 'ReactElement<any, any>'.
  Named property 'type' of types 'VNode<RendererNode, RendererElement, { [key: string]: any; }>' and 'ReactElement<any, any>' are not identical.

1493     interface Element extends VNode {}
                   ~~~~~~~

node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:1500:15 - error TS2430: Interface 'IntrinsicElements' incorrectly extends interface 'NativeElements'.
  Types of property 'a' are incompatible.
    Type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>' is not assignable to type 'ElementAttrs<AnchorHTMLAttributes>'.
      Type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>' is not assignable to type 'AnchorHTMLAttributes'.
        Types of property ''aria-relevant'' are incompatible.
          Type '"all" | "text" | "additions" | "additions text" | "removals" | "additions removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined' is not assignable to type '"all" | "text" | "additions" | "additions text" | "removals" | undefined'.
            Type '"additions removals"' is not assignable to type '"all" | "text" | "additions" | "additions text" | "removals" | undefined'.

1500     interface IntrinsicElements extends NativeElements {
                   ~~~~~~~~~~~~~~~~~

node_modules/@vue/runtime-dom/dist/runtime-dom.d.ts:1505:15 - error TS2320: Interface 'IntrinsicAttributes' cannot simultaneously extend types 'ReservedProps' and 'Attributes'.
  Named property 'key' of types 'ReservedProps' and 'Attributes' are not identical.

1505     interface IntrinsicAttributes extends ReservedProps {}
                   ~~~~~~~~~~~~~~~~~~~


Found 7 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
My versions:
```
    "@babel/core": "^7.15.5",
    "@storybook/addon-actions": "^6.3.8",
    "@storybook/addon-essentials": "^6.3.8",
    "@storybook/addon-links": "^6.3.8",
    "@storybook/vue3": "^6.3.8",
    "@vitejs/plugin-vue": "^1.6.1",
    "@vue/compiler-sfc": "^3.2.6",
    "babel-loader": "^8.2.2",
    "less": "^4.1.1",
    "less-loader": "^7",
    "typescript": "^4.3.2",
    "vite": "^2.5.4",
    "vue-loader": "^16.5.0",
    "vue-tsc": "^0.2.2"
```

**Comment by cwillinx** [comment]
Same in my case, only rm -rf ./node_modules/@types/react seems to help...

**Comment by SachaAvazashvili** [comment]
> Same in my case, only rm -rf ./node_modules/@types/react seems to help...

Had the same issue, had to add a prebuild hook script to delete that folder if it exists with `rimraf`:

```
  "scripts": {
    "prebuild": "rimraf ./node_modules/@types/react",
    "build": "vue-tsc --noEmit && vite build",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },

```

**Comment by tft7000** [comment]
You might want to check out https://github.com/johnsoncodehk/volar/discussions/592 for additional workarounds.

**Comment by RegisFrey** [comment]
Removing @types/react results in a failure on node_modules/@types/react-syntax-highlighter which fails the build when run alongside other scripts in my monorepo (but oddly not when run independently).

I'm still trying things to ID other causes and find a workaround that works in my case.

**Comment by jakehamilton** [comment]
> Bumping to prevent staling.

As far as I know this is still an issue and causing trouble in my Preact codebase. Working around it by deleting the node module myself is tedious and a bit hacky. Is there a way for Storybook to address this so non-react projects don't pull in react types?

**Comment by jadams2305** [comment]
Still an issue here. with Vue3 + storybook + PNPM.

Erros like:

```
../../../node_modules/.pnpm/@emotion+core@10.3.1_react@16.14.0/node_modules/@emotion/core/types/index.d.ts:17:8 - error TS7016: Could not find a declaration file for module 'react'. '/workspace/node_modules/.pnpm/react@16.14.0/node_modules/react/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react` if it exists or add a new declaration (.d.ts) file containing `declare module 'react';`

17 } from 'react'
          ~~~~~~~
```

**Comment by UkonnRa** [comment]
Still the issue here:

When `vue-tsc --emitDeclarationOnly`:

```
src/Scaffold.vue:6:10 - error TS2322: Type '{ class: string; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'.
  Property 'class' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'. Did you mean 'className'?
```

_Scaffold.vue_:

```
<template>
  <v-app :theme="theme" class="scaffold">
    <v-btn @click="toggleTheme">Toggle Theme: Current {{ theme }}</v-btn>
    <Hello></Hello>
    <World></World>
    <div class="chip-group"> <-- The problem is here
      <v-chip v-for="c in colors" :key="c" class="chip" :color="c">{{
        c
      }}</v-chip>
    </div>
  </v-app>
</template>
```

**Comment by cmcnicholas** [comment]
I've just got v7 alpha 54 working and this is still an issue, it creates a bad developer experience as it's not immediately apparent why this broke my monorepo setup.

**Comment by hyrumwhite** [comment]
Dealing with this myself. Seems related to the `@mdx-js/rollup` package. Deleting the @types/react folders fixes it, but that's a less than desirable fix.

**Comment by IanVS** [comment]
Would someone be able to help us out by creating a reproduction or set of steps we can follow to reproduce this issue in the latest 7.0 beta versions?  We've made some changes recently, which I think might have fixed this.

**Comment by K3TH3R** [comment]
> Would someone be able to help us out by creating a reproduction or set of steps we can follow to reproduce this issue in the latest 7.0 beta versions? We've made some changes recently, which I think might have fixed this.

@IanVS I've just been upgrading our Storybook to 7-beta.25 and I'm still seeing this with my Vue/Typescript repo. Can't do a repro quite yet, can try next week, but if I run a `yarn why @types/react` I'm seeing this:

```shell
yarn why @types/react
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@types/react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@types/react@18.0.26"
info Reasons this module exists
   - "@storybook#addon-essentials#@storybook#addon-docs#@mdx-js#react" depends on it
   - Hoisted from "@storybook#addon-essentials#@storybook#addon-docs#@mdx-js#react#@types#react"
info Disk size without dependencies: "1.34MB"
info Disk size with unique dependencies: "3.23MB"
info Disk size with transitive dependencies: "3.23MB"
info Number of shared dependencies: 3
✨  Done in 3.25s.
```

**Comment by l10rdev** [comment]
Did some one already update to storybook 7 is there still a problem?

**Comment by K3TH3R** [comment]
> Did some one already update to storybook 7 is there still a problem?

Yes, see my post directly above yours. I'm on Storybook 7.0.0-beta.25 and I needed to set a resolution for `@types/react` to the `skip-dependency` package to get past this issue.

**Comment by chakAs3** [comment]
@l10rdev 
yes this definitely gonna work for you 
```
"resolutions": {
    "@types/react": "https://registry.yarnpkg.com/@favware/skip-dependency/-/skip-dependency-1.0.2.tgz"
  }
```

just make sure to remove node_module, run again `  yarn  ` again and restart your VS Code.

**Comment by l10rdev** [comment]
@chakAs3 
Unfortunately we use npm. We now added a postinstall hock to remove this package.

**Comment by shilman** [comment]
Does anybody you a have a reproduction repo you can share on the latest 7.0 beta? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/7.0/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by K3TH3R** [comment]
> Does anybody you a have a reproduction repo you can share on the latest 7.0 beta? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/7.0/react/contribute/how-to-reproduce). Thank you! 🙏

@l10rdev @shilman I actually just setup a [sample repo](https://github.com/K3TH3R/composeStories-issue-storybook-7) for a separate issue I was seeing in [@storybookjs/testing-vue3](https://github.com/storybookjs/testing-vue3/issues/9). I just double-checked and I'm still seeing the issue with `class` in this repo:

![Screenshot 2023-01-24 at 3 24 15 pm](https://user-images.githubusercontent.com/11901111/214211895-1cd3f8d5-25f3-45bc-b80b-ad267471cdb3.png)

```shell
$ yarn why @types/react
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "@types/react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@types/react@18.0.27"
info Reasons this module exists
   - "@storybook#addon-essentials#@storybook#addon-docs#@mdx-js#react" depends on it
   - Hoisted from "@storybook#addon-essentials#@storybook#addon-docs#@mdx-js#react#@types#react"
info Disk size without dependencies: "1.35MB"
info Disk size with unique dependencies: "3.25MB"
info Disk size with transitive dependencies: "3.25MB"
info Number of shared dependencies: 3
✨  Done in 0.62s.
```

If I add the `skip-dependency` to the `resolutions` in this repo's `package.json` it also fixes the problem (after wiping/reinstalling `node_modules` and restarting VSCode).

**Comment by iamandrewluca** [comment]
The issue with TS error on `class` attribute was discussed [in this thread](https://github.com/johnsoncodehk/volar/discussions/592) a lot.
That is because Vue+TS projects have in `tsconfig.json` the property `jsx` set to `preserve`, which makes TypeScript JSX default to `@types/react`

**Comment by IanVS** [comment]
Correct me if I'm wrong, but the issue seems to be that one of our dependencies, `@mdx-js/react` includes `@types/react` in their `dependencies` (https://github.com/mdx-js/mdx/blob/f4d78be5c015e8fab48589efae9507d0304e5e94/packages/react/package.json#L45), and volar (and maybe other vue projects?) will pick up that types file if it is in your node_modules.  So, it seems like the only thing that can be done is to submit a PR to `@mdx-js/react` to move those types to a devDependency.  Would someone here like to do that?  I think it would be best coming from someone who is directly impacted, maybe @iamandrewluca since you seem pretty knowledgable about what's happening here?

**Comment by iamandrewluca** [comment]
https://github.com/mdx-js/mdx/discussions/2238

**Comment by IanVS** [comment]
It seems the maintainers of the MDX package so far are not receptive to making types optional.  I do not think there is anything that Storybook can do to address this, so I'm closing this issue.  For those of you here who feel strongly about this issue, please discuss in the thread that @iamandrewluca started: https://github.com/orgs/mdx-js/discussions/2238.

**Comment by iamandrewluca** [comment]
@IanVS after mdx folks suggested fixing this at the TS level, I think I may found the solution.
But it is like a floating bug, sometimes exists sometimes not.

**Comment by IanVS** [comment]
Personally I think mdx should use an optional peer dependency.  That is the most "correct" way to handle the situation, but they seem to be resisting that approach.  Anyone using typescript and react will have react types installed, and those using mdx without typescript should not have the types forced into their node_modules.  But again, it's unfortunately out of our hands here in Storybook.

**Comment by iamandrewluca** [comment]
Check this out. Just adding `"types": ["@vue/runtime-dom"]` fixes the issue.
And from my investigation of a nuxt3 project, there are no traces of Vue types in tsconfig

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1881266/214904926-1da5564e-377e-40a1-8fee-0605b2c31ca5.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1881266/214904957-4cc829fb-7773-4a62-a3b7-54aed74787f1.png">

**Comment by IanVS** [comment]
Note that if you specify `types`, you will lose all other definitely-typed types as well.  Be sure to read https://www.typescriptlang.org/tsconfig#types to understand what it does.

**Comment by iamandrewluca** [comment]
So this issue should be fixed by Vue frameworks/boilerplates authors, to make sure they include  those types.

> Note that if you specify types, you will lose all other definitely-typed types as well. Be sure to read [typescriptlang.org/tsconfig#types](https://www.typescriptlang.org/tsconfig#types) to understand what it does.

I suppose this is ok 🤔 

`types` is for global automatically types,

for example when you import from `react`, it will automatically infer types from `@types/react`

🤔

**Comment by iamandrewluca** [comment]
> Not if they're specified as optional in peerDependenciesMeta.

Tested right now locally, still installs them

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1881266/214907104-26b5633d-401d-4086-8e15-a3bb0e5645d0.png">

**Comment by iamandrewluca** [comment]
I want to give up )) I cannot reproduce the issue in my repo anymore 🤣
Also, it seems that `types` also won't help. If TypeScript will find `@types/react` in the import tree it will still show the error.

So this can be a floating bug, depending in what order TS will start analysing the files 🤔

**Comment by IanVS** [comment]
There are a lot of people subscribed on this issue, and I don't want to continue a back and forth about npm behavior here (happy to dig in more on discord.gg/storybook, though!).  Maybe you have an older npm or something, as of recent versions, it should be respecting `optional: true`.  See https://github.com/npm/rfcs/issues/221#issuecomment-695127530 and https://github.com/npm/cli/issues/2615#issuecomment-784509497.

**Comment by iamandrewluca** [comment]
About NPM. Yes, I have v8, and v9 fixes that.
But it seems the problem is not the `@types/react` existence, but when something imports it.

I have some more insight, that sends me to the `@apollo/client` library.

I have Fresh Nuxt3 with Storybook. Everything works fine.
I want to add Apollo. Adding Apollo Nuxt module.
In Nuxt3 the module types are automatically augmented.
And after investigation, it seems that deep down in some files there is a `react` import in a *.ts file in `@apollo/client`
