### PR TITLE
Rethrowing errors caught while loading stories

### PR DESCRIPTION
**Pull request by GreenGremlin**
Issue:

Fixes (partially) https://github.com/storybookjs/storybook/issues/13151

## What I did

Ensured that errors encountered while loading stories are re-thrown without preventing subsequent stories from loading.

@luke-j added the try / catch in https://github.com/storybookjs/storybook/pull/10974, in his description he says, "Re-throwing the error is not an option as that is also swallowed." However, re-throwing asynchronously, in a `setTimeout`, prevents it from getting swallowed.

## How to test

- Is this testable with Jest or Chromatic screenshots? Possibly, though I'm not sure how to go about mocking a module load error. I'm open to suggestions.
- Does this need a new example in the kitchen sink apps? No
- Does this need an update to the documentation? No

If your answer is yes to any of these, please make sure to include it in your PR.

### CODE REVIEW

**Comment by shilman** [comment]
@GreenGremlin can you explain the rationale here a bit more? what part of the problem does it solve?

**Comment by GreenGremlin** [comment]
> @GreenGremlin can you explain the rationale here a bit more? what part of the problem does it solve?
> 
> EDIT: possibly this one? [#10876 (comment)](https://github.com/storybookjs/storybook/issues/10876#issuecomment-748615875)

@shilman this ensures that ANY error encountered while loading stories is more visible. For me, it was a singleton that threw an error because there was some missing context when it was loaded in Storybook. Normally, the thrown error would have been very obvious in the console. However, because it was caught and logged as a warning, I ended up spending over an hour trying to figure out why I was getting undefined imports.

Before https://github.com/storybookjs/storybook/pull/10974, these errors were completely swallowed. With that PR, the caught errors are now logged as a warning, which is definitely an improvement, but still not ideal. This change takes it a step further and ensures that errors are output as ERRORS, but still do not prevent other stories from loading.

**Review by shilman — APPROVED** [review]
Thanks for the detailed explanation @GreenGremlin. I'm going to test it out before merging, but SGTM. I'd also like a second opinion @ghengeveld @tmeasday @ndelangen @tooppaaa because it seems like a somewhat awkward pattern.

**Comment by tmeasday** [comment]
I wonder if we should just be more aggressive and red-box the whole storybook if any story file throws an error? It seems sort of weird that we are so conservative about it (and it has caused a lot of problems in the past).

I guess that'd be a breaking change, but my questions about this PR are:

1. Why do we need to `setTimeout(,0)` it? I see the comment that the error is swallowed otherwise, but where? why? can we avoid that?
2. Can we just use `logger.error` or something rather than a `setTimeout` to make it more obvious? I'm still wondering about 1. however.

**Comment by GreenGremlin** [comment]
> I guess that'd be a breaking change, but my questions about this PR are:
> 
> 1. Why do we need to `setTimeout(,0)` it? I see the comment that the error is swallowed otherwise, but where? why? can we avoid that?
> 2. Can we just use `logger.error` or something rather than a `setTimeout` to make it more obvious? I'm still wondering about 1. however.

1. I'm not sure where it is being caught. Wherever it is being caught doesn't log the caught error, so it's difficult to tell. Yes, ideally we would either not catch the error, or log it to the redbox, as mentioned in the link above. But, neither of those seem to be easy fixes and this is a pretty serious issue that needs to be addressed ASAP. Currently, the error is logged without a call stack, which makes it near impossible to track down errors with generic errors like "undefined is not a function".
2. The trouble with `logger.error` is that it logs the call stack where you call it, not where the error occurred. Re-throwing is definitely preferred.

**Comment by tmeasday** [comment]
OK, that's a fair point. I agree a temporary fix makes sense.

> Wherever it is being caught doesn't log the caught error, so it's difficult to tell. 

Can you try just putting a `debugger` statement exactly before the error is thrown and trace what happens to it using the browser debugger?

**Comment by ndelangen** [comment]
@tmeasday I'm ping-ing you on this, as you said, this would be an OK short term fix... but here we are, a few moments later, and started major work on 7.0...

I updated this branch with next, what would you like to do here?

**Comment by tmeasday** [comment]
Let's just make sure we don't swallow errors (and redbox them prominently) if they are thrown from a story file. cc @ghengeveld who was documenting a list of our error states - let's make sure we address such errors as part of that work.

Sorry this got lost @GreenGremlin
