### ISSUE TITLE
"Uncaught TypeError: api.getAddonsShortcuts is not a function" when adding `@storybook/addon-backgrounds` to Storybook v6.2.9 (also doesn't work on v6.3.2)

### ISSUE THREAD

**Issue by ahayes91** [storybookjs/storybook#15455]
**Describe the bug**
I added `@storybook/addon-backgrounds` to our existing Storybook instance and started this error in the console:

```
Uncaught TypeError: api.getAddonsShortcuts is not a function
    at getAddonsShortcuts (vendors~main.manager.bundle.js:49907)
    at vendors~main.manager.bundle.js:49937
    at mountMemo (vendors~main.manager.bundle.js:139332)
    at Object.useMemo (vendors~main.manager.bundle.js:139628)
    at useMemo (vendors~main.manager.bundle.js:155977)
    at useMenu (vendors~main.manager.bundle.js:49936)
    at Object.mapper [as current] (vendors~main.manager.bundle.js:49966)
    at ManagerConsumer (vendors~main.manager.bundle.js:66702)
    at renderWithHooks (vendors~main.manager.bundle.js:138693)
    at mountIndeterminateComponent (vendors~main.manager.bundle.js:141372)
```

So then I tried to update our Storybook instance, but it won't load and gives the same console error (no error on build of Storybook though).

![Screenshot 2021-07-01 at 16 01 43](https://user-images.githubusercontent.com/8914051/124146579-ce34bb80-da85-11eb-8108-473601498437.png)

We have a package for our Storybook instance in our monorepo, and the package.json has the following:

Before updating Storybook:
```json
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@storybook/addon-a11y": "^6.2.9",
    "@storybook/addon-actions": "^6.2.9",
    "@storybook/addon-viewport": "^6.2.9",
    "@storybook/addon-backgrounds": "6.2.9",
    "@storybook/addon-docs": "^6.2.9",
    "@storybook/react": "^6.2.9",
    "@storybook/theming": "^6.2.9",
    "storybook-addon-designs": "6.0.0-alpha.3",
    "babel-loader": "^8.2.0",
    "msw-storybook-addon": "1.1.0",
    "react-is": "^17.0.1",
    "react-test-renderer": "16.14.0",
    "svg-inline-loader": "^0.8.0"
  },
  "msw": {
    "workerDirectory": "public"
  }
```

After updating Storybook:
```json
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@storybook/addon-a11y": "^6.3.2",
    "@storybook/addon-actions": "^6.3.2",
    "@storybook/addon-viewport": "^6.3.2",
    "@storybook/addon-backgrounds": "6.3.2",
    "@storybook/addon-docs": "^6.3.2",
    "@storybook/react": "^6.3.2",
    "@storybook/theming": "^6.3.2",
    "storybook-addon-designs": "6.0.0",
    "babel-loader": "^8.2.0",
    "msw-storybook-addon": "1.1.0",
    "react-is": "^17.0.1",
    "react-test-renderer": "16.14.0",
    "svg-inline-loader": "^0.8.0"
  },
  "msw": {
    "workerDirectory": "public"
  }
```

**To Reproduce**
I will try and create a repro repository for this over the next couple of days 🤞 It's a little bit tricky to recreate our exact scenario from our monorepo setup, but will have a nosy at https://storybook.js.org/docs/react/contribute/how-to-reproduce.

**System**
Please paste the results of `npx sb@next info` here.

Before updating Storybook:

```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.13.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 78.9.0
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.2.9 => 6.2.9 
    @storybook/addon-actions: ^6.2.9 => 6.3.1 
    @storybook/react: ^6.2.9 => 6.2.9 
    @storybook/theming: ^6.2.9 => 6.2.9 
```

After updating Storybook:

```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.13.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 78.9.0
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-a11y: ^6.3.2 => 6.3.2 
    @storybook/addon-actions: ^6.3.2 => 6.3.2 
    @storybook/react: ^6.3.2 => 6.3.2 
```

**Additional context**
You might notice we are using Mock Service Worker with Storybook with the `msw-storybook-addon` - not sure if that makes any difference or not.
I also tried to remove some of the addons in favour of the `@storybook/addon-essentials` but I had the same issue.

**Comment by shilman** [comment]
Did you try removing `node_modules` and/or lockfiles and reinstalling?

**Comment by ahayes91** [comment]
> Did you try removing `node_modules` and/or lockfiles and reinstalling?
> 
> It looks like your install has an old version of Storybook installed and it's using that. `api.getAddonsShortcuts` was added in 6.3.

Thanks for that info, that's really helpful! I have a feeling this might be happening because of module hoisting in our monorepo (looks like there are other packages in there with older versions of Storybook that this might be falling back on somewhere) - doing some experimentation with https://classic.yarnpkg.com/blog/2018/02/15/nohoist/ now to see if I can sort it. I'll close this ticket once I've confirmed the solution, thank you!

**Comment by ahayes91** [comment]
Yep this was definitely it - I had older versions of Storybook addons elsewhere in my monorepo and they were conflicting, causing the error. Thanks for the help!

**Comment by yuriteixeira** [comment]
Just to mention that I have a similar issue in my CI machines and removing `node_modules` + running `yarn cache clean` fixed the issue \o/
