### ISSUE TITLE
[Bug]: "Uncaught TypeError: Vv.addons.addPanel is not a function" after upgrading from 7.6.17 to 8.0.0

### ISSUE THREAD

**Issue by gabrielhpugliese** [storybookjs/storybook#26472]
### Describe the bug

I have run `npx storybook@latest upgrade` and accepted all suggested changes and the server runs successfully as before. But when I open the page at `http://localhost:6006/` I get and blank screen and these errors on Chrome's console:

```
Uncaught TypeError: Vv.addons.addPanel is not a function
    at register-bundle.js:37:8825
    at chunk-Q3RBXCN3.js:35:34854
    at Array.forEach (<anonymous>)
    at AddonStore.loadAddons (chunk-Q3RBXCN3.js:35:34838)
    at ReactProvider.handleAPI (runtime.js:1:640)
    at Object.init (chunk-Q3RBXCN3.js:21:53699)
    at chunk-Q3RBXCN3.js:35:35720
    at Array.forEach (<anonymous>)
    at ManagerProvider.initModules (chunk-Q3RBXCN3.js:35:35679)
    at commitHookEffectListMount (chunk-3F3RRPB3.js:98:55191)
The above error occurred in the <EffectOnMount> component:

    at EffectOnMount (http://localhost:6006/sb-manager/chunk-Q3RBXCN3.js:35:37458)
    at ManagerProvider (http://localhost:6006/sb-manager/chunk-Q3RBXCN3.js:35:35619)
    at Location (http://localhost:6006/sb-manager/chunk-Q3RBXCN3.js:13:16387)
    at Main (http://localhost:6006/sb-manager/chunk-AQBE2B7B.js:183:12486)
    at Router (http://localhost:6006/sb-manager/chunk-Q3RBXCN3.js:13:7100)
    at LocationProvider (http://localhost:6006/sb-manager/chunk-Q3RBXCN3.js:13:17225)
    at r3 (http://localhost:6006/sb-manager/chunk-AQBE2B7B.js:15:17151)
    at Root3 (http://localhost:6006/sb-manager/chunk-AQBE2B7B.js:183:12268)
```

### To Reproduce

I have no idea how to reproduce this except of what I have described up there. It happens on my company's huge project.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm <----- active
  Browsers:
    Chrome: 122.0.6261.112
    Edge: 122.0.2365.80
    Safari: 17.2.1
  npmPackages:
    @storybook/addon-actions: ^8.0.0 => 8.0.0
    @storybook/addon-docs: ^8.0.0 => 8.0.0
    @storybook/addon-essentials: ^8.0.0 => 8.0.0
    @storybook/addon-knobs: ^7.0.2 => 7.0.2
    @storybook/addon-links: ^8.0.0 => 8.0.0
    @storybook/addon-mdx-gfm: ^8.0.0 => 8.0.0
    @storybook/addon-viewport: ^8.0.0 => 8.0.0
    @storybook/addon-webpack5-compiler-babel: ^3.0.3 => 3.0.3
    @storybook/addons: ^7.6.17 => 7.6.17
    @storybook/blocks: ^8.0.0 => 8.0.0
    @storybook/icons: ^1.2.9 => 1.2.9
    @storybook/react: ^8.0.0 => 8.0.0
    @storybook/react-webpack5: ^8.0.0 => 8.0.0
    @storybook/test-runner: ^0.17.0 => 0.17.0
    chromatic: ^11.0.7 => 11.0.7
    eslint-plugin-storybook: ^0.8.0 => 0.8.0
    storybook: ^8.0.0 => 8.0.0
    storybook-addon-mock: ^4.3.0 => 4.3.0
    storybook-react-i18next: ^2.1.1 => 2.1.1
```
```


### Additional context

How can I proceed to debug this? Just let me know I can bring more info
