### ISSUE TITLE
addon-knobs/react - Rendered more hooks than during the previous render

### ISSUE THREAD

**Issue by brookemitchell** [storybookjs/storybook#8085]
When using addon-knobs and adding the decorator at the **`.storiesOf` level** I get the error.

```
bundle.js:300234 Error: Rendered more hooks than during the previous render.
    at useHook (bundle.js:74282)
    at useMemoLike (bundle.js:74309)
    at useEffect (bundle.js:74407)
    at registerKnobs (bundle.js:70880)
    at wrapper (bundle.js:70748)
    at bundle.js:74655
```

This could only be an issue on react-native, and only occurs for me when:

1. Using react-native (I haven't tested vanilla react)
2. Registering  `storiesOf('aStory', module).addDecorator(withKnobs)`

**To Reproduce**
Create a story that uses `addon-knobs` at the `storiesOf` level, with react-native.

Example:
```
storiesOf('X', module)
  .addDecorator(withKnobs)
  .add('X', () => (<View />), {}, )
```

Once I move the `withKnobs` decorator to the global level, everything is good again 👍 👍 👍  
```
// config.ts
import {  addDecorator } from '@storybook/react-native'
import { withKnobs } from '@storybook/addon-knobs/react'

addDecorator(withKnobs)
```

So no real complaint here, but thought I should mention the issue. This seems very likely related to https://github.com/storybookjs/storybook/issues/6679 . Thought the fix might be useful to someone else in this slightly specific case.

**Comment by shilman** [comment]
@Hypnosphi any ideas here?

**Comment by Hypnosphi** [comment]
@brookemitchell local `withKnobs` work OK in my own setup with 5.2.0.
Can you please create a GitHub repo with a minimal reproduction?

**Comment by Hypnosphi** [comment]
This is probably specific to react-native. Will have a look.

**Comment by brookemitchell** [comment]
Sure give me a couple hours then I'll be free to spin up a minimal repro. It is definitely only applicable to react-native

**Comment by Hypnosphi** [comment]
@brookemitchell Hi, did something go wrong with the repro?

**Comment by brookemitchell** [comment]
Sorry no just haven't had time. I'll close and revisit the repro when I get time later this week.
