### ISSUE TITLE
[5.2.1] IE11 support broken when using addon-info

### ISSUE THREAD

**Issue by matthew-was** [storybookjs/storybook#8253]
**Describe the bug**
After upgrading to storybook 5.2.1 from 5.0.11 I was unable ot use storybook in IE11 due to a compilation error. I was able to track this down to the bundled module from react-element-to-jsx-string where there are arrow functions.

**To Reproduce**
Using a project with storybook using storybook/addon-info
Start the project using yarn storybook
navigate to the storybook served page in IE11 and see an error in the console

**Expected behavior**
There shouldn't be an error in the console and and storybook should load

**Screenshots**
![storybook error](https://user-images.githubusercontent.com/4680912/65952784-85784a80-e43a-11e9-97db-316ee8b59f23.png)

**Code snippets**
Code from react-element-to-jsx-string
```javascript
var lib = createCommonjsModule(function (module, exports) {
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = (object) => Object
    .getOwnPropertySymbols(object)
    .filter((keySymbol) => object.propertyIsEnumerable(keySymbol));

});
```

**System:**
Environment Info:
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.1/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.1
  npmPackages:
    @storybook/addon-actions: 5.2.1 => 5.2.1 
    @storybook/addon-info: 5.2.1 => 5.2.1 
    @storybook/addon-links: 5.2.1 => 5.2.1 
    @storybook/addons: 5.2.1 => 5.2.1 
    @storybook/react: 5.2.1 => 5.2.1 

**Additional context**
While this is mainly a problem within react-element-to-jsx-string would it be possible to version lock this dependency at 14.0.2 as this was working previously.

**Comment by shilman** [comment]
FYI `addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. It’s been released in Storybook 5.2, and AFAIK runs in IE. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by matthew-was** [comment]
thanks @shilman, definitely going to look into docs in the future, just looking to upgrade at this point.
