### ISSUE TITLE
[Bug]: @storybook/react-webpack5 v7.3 crashes without @storybook/manager-api

### ISSUE THREAD

**Issue by dmaier-indeed** [storybookjs/storybook#23876]
### Describe the bug

When updating `@storybook/react-webpack5` to v7.3, Storybook failed to launch. After debugging, I found Storybook was not able to resolve `@storybook/manager-api`. Before v7.3, `@storybook/react-webpack5` shipped with `@storybook/manager-api` in `dependencies`. 

The fix is simple: consumers need to install `@storybook/manager-api`, however this should either be shipped within `@storybook/react-webpack5` or listed as a peer dependency

Crash log
```
> storybook build --webpack-stats-json -o storybook-static
@storybook/cli v7.3.1
info => Cleaning outputDir: /storybook-static
Attention: We've detected that you're using the following addons in versions which are known to be incompatible with Storybook 7:
- @storybook/addon-queryparams@6.2.9
Please be aware they might not work in Storybook 7. Reach out to their maintainers for updates and check the following Github issue for more information:
https://github.com/storybookjs/storybook/issues/20529
info => Loading presets
info Found existing addon "@storybook/addon-actions", skipping.
info Found existing addon "@storybook/addon-toolbars", skipping.
WARN   Failed to load preset: "/builds/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js"
ERR! Error: Cannot find module '@storybook/manager-api/package.json'
ERR! Require stack:
ERR! - /builds/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js
ERR! - /builds/node_modules/@storybook/core-common/dist/index.js
ERR! - /builds/node_modules/@storybook/telemetry/dist/index.js
ERR! - /builds/node_modules/@storybook/cli/dist/generate.js
ERR! - /builds/node_modules/@storybook/cli/bin/index.js
ERR! - /builds/node_modules/storybook/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
ERR!     at Function.Module._resolveFilename (/builds/node_modules/esbuild-register/dist/node.js:4768:36)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:125:19)
ERR!     at getAbsolutePath (/builds/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js:3:323)
ERR!     at Object.<anonymous> (/builds/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js:3:785)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1198:14)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
ERR!     at Object.newLoader (/builds/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Object.extensions..js (/builds/node_modules/esbuild-register/dist/node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1076:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1100:19)
ERR!     at require (node:internal/modules/cjs/helpers:119:18)
ERR!     at interopRequireDefault (/builds/node_modules/@storybook/core-common/dist/index.js:6:21)
ERR!     at getContent (/builds/node_modules/@storybook/core-common/dist/index.js:13:332)
ERR!     at loadPreset (/builds/node_modules/@storybook/core-common/dist/index.js:13:517)
ERR!  Error: Cannot find module '@storybook/manager-api/package.json'
ERR! Require stack:
ERR! - /builds/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js
ERR! - /builds/node_modules/@storybook/core-common/dist/index.js
ERR! - /builds/node_modules/@storybook/telemetry/dist/index.js
ERR! - /builds/node_modules/@storybook/cli/dist/generate.js
ERR! - /builds/node_modules/@storybook/cli/bin/index.js
ERR! - /builds/node_modules/storybook/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
ERR!     at Function.Module._resolveFilename (/builds/node_modules/esbuild-register/dist/node.js:4768:36)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:125:19)
ERR!     at getAbsolutePath (/builds/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js:3:323)
ERR!     at Object.<anonymous> (/builds/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js:3:785)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1198:14)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
ERR!     at Object.newLoader (/builds/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at Object.extensions..js (/builds/node_modules/esbuild-register/dist/node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1076:32)
ERR!     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1100:19)
ERR!     at require (node:internal/modules/cjs/helpers:119:18)
ERR!     at interopRequireDefault (/builds/node_modules/@storybook/core-common/dist/index.js:6:21)
ERR!     at getContent (/builds/node_modules/@storybook/core-common/dist/index.js:13:332)
ERR!     at loadPreset (/builds/node_modules/@storybook/core-common/dist/index.js:13:517) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/builds/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js',
ERR!     '/builds/node_modules/@storybook/core-common/dist/index.js',
ERR!     '/builds/node_modules/@storybook/telemetry/dist/index.js',
ERR!     '/builds/node_modules/@storybook/cli/dist/generate.js',
ERR!     '/builds/node_modules/@storybook/cli/bin/index.js',
ERR!     '/builds/node_modules/storybook/index.js'
ERR!   ]
ERR! }
```

### To Reproduce

Install Storybook with `@storybook/react-webpack5` preset but do not install `@storybook/manager-api`. Attempt to launch Storybook

### System

```shell
Environment Info:

  System:
    OS: macOS 13.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Firefox: 115.0.3
    Safari: 16.6
  npmPackages:
    @storybook/addon-a11y: ^7.3.1 => 7.3.1 
    @storybook/addon-actions: ^7.3.1 => 7.3.1 
    @storybook/addon-essentials: ^7.3.1 => 7.3.1 
    @storybook/addon-interactions: ^7.3.1 => 7.3.1 
    @storybook/addon-links: ^7.3.1 => 7.3.1 
    @storybook/addon-queryparams: ^6.2.9 => 6.2.9 
    @storybook/addon-toolbars: ^7.3.1 => 7.3.1 
    @storybook/jest: ^0.1.0 => 0.1.0 
    @storybook/manager-api: ^7.3.1 => 7.3.1 
    @storybook/react: ^7.3.1 => 7.3.1 
    @storybook/react-webpack5: ^7.3.1 => 7.3.1 
    @storybook/test-runner: ^0.13.0 => 0.13.0 
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

### Additional context

New bug as of version 7.3.0. Most likely from [commit f70f0508f182b475c65a5b9d87444421ef8790eb ](https://github.com/storybookjs/storybook/pull/23496/commits/f70f0508f182b475c65a5b9d87444421ef8790eb)

**Comment by mkosir** [comment]
Can reproduce the same issue, but would also add that it will fail with same error in case project was using `@storybook/addons`, `"@storybook/theming"`,... or any other dependency that was removed in mentioned [commit](https://github.com/storybookjs/storybook/pull/23496/commits/f70f0508f182b475c65a5b9d87444421ef8790eb).

**Comment by yannbf** [comment]
Hey @mkosir @dmaier-indeed thanks for reporting the issue! I'm unfortunately not able to reproduce it, can you tell me what I'm doing wrong?
https://stackblitz.com/edit/github-j83rie?file=package.json

**Comment by mkosir** [comment]
Hey @yannbf 👋 
To reproduce:
- clone and `npm i` [react-parallax-tilt](https://github.com/mkosir/react-parallax-tilt) repo
- run `npm run start` - storybook works
- remove `@storybook/addon-essentials` or `@storybook/manager-api` and `npm i`
-  run `npm run start` - storybook fails

**Comment by yannbf** [comment]
Thank you so much @mkosir!

I followed your steps and removed @storybook/manager-api, but there were no issues.
When I removed `@storybook/manager-api` AND `@storybook/addon-essentials`, then I had an issue, which was slightly different than the one originally reported, but similar:

```
ERR! Error: Cannot find module '@storybook/components/package.json'
ERR! Require stack:
ERR! - /Users/yannbraga/experiments/react-parallax-tilt/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js
```

Regardless, we tracked the issue and released 7.3.2 which should be working correctly now (I tried on your repro).

**Comment by mkosir** [comment]
Thank you @yannbf, that was fast 🚀 

> I followed your steps and removed @storybook/manager-api, but there were no issues.
When I removed @storybook/manager-api AND @storybook/addon-essentials, then I had an issue, which was slightly different than the one originally reported, but similar:

Thanks you are correct, there is no issues with storybook running if we remove just `@storybook/manager-api`.

In my case other scripts failed such as lint, typescript check etc. since [importing](https://github.com/mkosir/react-parallax-tilt/blob/main/.storybook/manager.ts#L1) `addons` to set the theme.
With Storybook upgrade [change](https://github.com/mkosir/react-parallax-tilt/commit/fbffbff0334e20cf5d297c97e33e9cb464af0337) was needed from
`import { addons } from '@storybook/addons';`
to
`import { addons } from '@storybook/manager-api';`

**Comment by dmaier-indeed** [comment]
Confirmed I no longer see the issue with version `7.3.2` 👍

**Comment by mkosir** [comment]
It looks like we have a regression in `v7.4.0`.

**Comment by yannbf** [comment]
> It looks like we have a regression in `v7.4.0`.

Confirmed it was not a regression. It's all good!
