### ISSUE TITLE
After upgrading from 5.3 to 6 getting below error

### ISSUE THREAD

**Issue by santhoshmp89** [storybookjs/storybook#16200]
Uncaught TypeError: backgrounds.find is not a function
    at getBackgroundColorByName (vendors~main.manager.bundle.js:21115)
    at vendors~main.manager.bundle.js:21278
    at updateMemo (vendors~main.manager.bundle.js:239203)
    at Object.useMemo (vendors~main.manager.bundle.js:239660)
    at useMemo (vendors~main.manager.bundle.js:256590)
    at vendors~main.manager.bundle.js:21277
    at renderWithHooks (vendors~main.manager.bundle.js:238543)
    at updateFunctionComponent (vendors~main.manager.bundle.js:240774)
    at updateSimpleMemoComponent (vendors~main.manager.bundle.js:240712)
    at beginWork (vendors~main.manager.bundle.js:242427)

**Comment by santhoshmp89** [comment]
can someone help me

**Comment by shilman** [comment]
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#backgrounds-addon-has-a-new-api

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
