### ISSUE TITLE
[Bug]: Error `Cannot find module @storybook/global` is thrown when Babel is used with CommonJS modules in 7.6+

### ISSUE THREAD

**Issue by soren121** [storybookjs/storybook#26126]
### Describe the bug

When Webpack & Babel are used, and `@babel/preset-env` is configured with `modules: 'commonjs'`, a runtime error is thrown when viewing stories that import `action` from `@storybook/addon-actions`.

This worked in 7.5.3, and is a regression starting from 7.6.

![Screenshot 2024-02-20 at 1 15 34 PM](https://github.com/storybookjs/storybook/assets/295939/45668619-e637-43ca-a8fc-b75ca1b630f4)

To be honest, I'm not positive that this is a bug in Storybook. My gut feeling is that the best solution could be to ask users to fix their Babel configs to use `modules: 'auto'` as recommended [in their docs](https://babeljs.io/docs/babel-preset-env#modules), but in that case it should be added to the migration notes as it represents a BC break from 7.5.

### To Reproduce

* Repo: https://github.com/soren121/storybook-addons-bug-repro
* StackBlitz demo: https://stackblitz.com/github/soren121/storybook-addons-bug-repro

Navigate to the Button example in Storybook, and a runtime error should be thrown.

### System

```bash
Storybook Environment Info:

  System:
    OS: macOS 13.6.4
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn <----- active
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 7.5.2 - ~/.asdf/shims/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.3.1
  npmPackages:
    @storybook/addon-essentials: ^7.6.16 => 7.6.17 
    @storybook/addon-interactions: ^7.6.16 => 7.6.17 
    @storybook/addon-links: ^7.6.16 => 7.6.17 
    @storybook/addon-onboarding: ^1.0.11 => 1.0.11 
    @storybook/blocks: ^7.6.16 => 7.6.17 
    @storybook/react: ^7.6.16 => 7.6.17 
    @storybook/react-webpack5: ^7.6.16 => 7.6.17 
    @storybook/test: ^7.6.16 => 7.6.17 
    storybook: ^7.6.16 => 7.6.17
```

### Additional context

A similar bug was tracked in #25130, but it appears there is more than one cause, as others still report issues after a fix was identified.

**Comment by yannbf** [comment]
Hey there! Thank you so much for reporting. We created a fix for Storybook 8 and released a canary containing it which can be tested by running:

```
npx storybook@0.0.0-pr-26145-sha-32b8346f upgrade
```

Once the fix is confirmed and merged, we will patch it to Storybook 7.6 as well.

Would you mind testing it out and letting us know? 🙏

**Comment by soren121** [comment]
@yannbf Yes, that looks to be working now! I migrated the reproduction and the bug no longer appears.

**Comment by nclskfm** [comment]
> Once the fix is confirmed and merged, we will patch it to Storybook 7.6 as well.

Hi @yannbf, unfortunately, there is still no fix for 7.6. Can we expect a fix for 7.6 or should we upgrade to SB8 soon?

**Comment by JReinhold** [comment]
@nclskfm v7.6.18 has been released now with this fix.

https://github.com/storybookjs/storybook/releases/tag/v7.6.18
