### ISSUE TITLE
Storybook v.6.3.6 - Webpack 5 - Loading forever

### ISSUE THREAD

**Issue by Huespal** [storybookjs/storybook#15719]
**Describe the bug**
Storybook is loading forever.

**To Reproduce**
Start storybook (start-storybook -p 6007 -s ./public).
Wait forever.

P.D:
I've tried reproduction but an error occurs
```
yarn install
An error occurred while executing: `yarn install`
Command output was:
Type Error: Cannot read property 'match' of undefined


🚨 Dependencies installation failed
🚨 Failed to create repro
```

**System**
Mac OSX - Latest version

**Additional context**

.storybook/main.js
```
const path = require('path');
const dotenv = require('dotenv-webpack');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  stories: ['../src/components/**/*stories.js'],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-a11y'
  ],
  core: {
    builder: 'webpack5'
  },
  webpackFinal: async config => {
    config.resolve.fallback.fs = false;
    config.resolve.fallback.stream = false;
    config.plugins.push(new dotenv());
    config.plugins.push(
      new CopyPlugin({
        patterns: [
          {
            from: path.resolve(__dirname, '../public/fonts'),
            to: 'fonts/'
          }
        ]
      })
    );
    config.plugins = config.plugins.filter(p => String(p.resourceRegExp) !== '/core-js/');
    return config;
  }
};
```

dotenv-webpack installed as a devDependency (v.6.0.4)
storybook and related libs (addons, etc) at v6.3.6.
Webpack at v5.36.2

Web Output
![SB Fail](https://user-images.githubusercontent.com/4157755/127622411-1838bbe9-f115-491a-b57d-1d656f9a47f9.png)

Terminal output
```
info @storybook/react v6.3.6
info 
info => Loading presets
info => Serving static files from ././public at /
info => Loading 1 config file in "/Users/username/.storybook"
info => Loading 8 other files in "/Users/username/.storybook"
info => Adding stories defined in "/Users/username/.storybook/main.js"
info => Using implicit CSS loaders
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/1 entries 0/0 dependencies 0/0 modules
info => Using cached manager
99% done plugins webpack-hot-middlewarewebpack built preview d1a3b3ded0a609aac380 in 12400ms
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 6.3.6 started                          │
│   13 s for preview                                 │
│                                                    │
│    Local:            http://localhost:6007/        │
│    On your network:  http://192.168.1.106:6007/    │
│                                                    │
╰────────────────────────────────────────────────────╯
<i> [webpack-dev-middleware] wait until bundle finished: /vendors-node_modules_storybook_ui_node_modules_storybook_components_dist_esm_ScrollArea_Overl-dcb01a.manager.bundle.js
<i> [webpack-dev-middleware] wait until bundle finished: /vendors-node_modules_storybook_ui_node_modules_storybook_components_dist_esm_ScrollArea_Globa-dbae17.manager.bundle.js
<i> [webpack-dev-middleware] wait until bundle finished: /vendors-node_modules_storybook_ui_node_modules_storybook_components_dist_esm_tooltip_WithTooltip_js.manager.bundle.js
<i> [webpack-dev-middleware] wait until bundle finished: /iframe.html?id=*&viewMode=story
99% done plugins webpack-hot-middlewarewebpack built preview d03d8fd9ef7412693598 in 1008ms
```

If I `build` instead of `start` storybook, It completes, but I have the annoying DefinePlugin message:
```
WARN DefinePlugin
WARN Conflicting values for 'process.env'
```

Thank you

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by Huespal** [comment]
Hello Shilman.

Thank you for your answer.
As I said before, I tried the repro, but it failed.

**Comment by IgnacioNMiranda** [comment]
Having exactly the same error, still don't know how to fix it ):

**Comment by yoavniran** [comment]
Im having the same issue as described here and in: #14405 
Both on 6.4.9 and 6.3.12.
Webpack: 5.65.0

After upgrading from 6.2.2 and webpack 4.

I tried removing all addons and stories but process  hangs on: 

```
99% done plugins webpack-hot-middlewarewebpack built preview 0ca4f1dc51ae93289621 in 14279ms
```

on 6.3.12 I also see the warning about define plugin (_Conflicting values for 'process.env'_) and this error in the browser:

```

bootstrap:27 Uncaught TypeError: util.inherits is not a function
    at Object../node_modules/assert/assert.js (assert.js:164)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at utility.js:32
    at Object../node_modules/doctrine/lib/utility.js (utility.js:33)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at typed.js:27
    at Object../node_modules/doctrine/lib/typed.js (typed.js:1304)
    at __webpack_require__ (bootstrap:24)
```

The manager loads as I see elements on the page including my custom logo. The preview seems hanging with the spinner.

With 6.4.9 the process would eventually break on flow(bin) types in my stories. 6.3.12 simply hangs forever.

I also tried deleting node_modules for good measure but no difference.

The repo with the updated branch can be found on this [react-uploady branch](https://github.com/rpldy/react-uploady/tree/upgrade-sb-webpack)

**Comment by shilman** [comment]
@yoavniran nothing is hanging here, it's just bad formatting:

```
99% done plugins webpack-hot-middleware
webpack built preview 0ca4f1dc51ae93289621 in 14279ms
```

Are there any errors in the browser console in 6.4?

**Comment by OllyHodgson** [comment]
Is this a duplicate of #14405 (or at least something very similar)?

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
