### PR TITLE
fix(components): move react-syntax-highlighter types to dev deps

### LINKED ISSUE #12505: Storybook v6 + vue + tsx -> tsc errors: conflict types with @types/react
**Describe the bug**
After migration from 5.2 to 6 `npx tsc` throw errors: 
- `Property 'class' does not exist on type 'DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>'`
- `Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<...>, Record<...>>'.`

**To Reproduce**

1. Clone 'https://github.com/voskresla/sb-migrate-reproduce'
2. Run 'npm i && npx tsc'

**Expected behavior**
No errors )

**Screenshots**

**Code snippets**

**System:**
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
    Safari: 13.1
  npmPackages:
    @storybook/addon-knobs: ^6.0.21 => 6.0.21 
    @storybook/source-loader: ^6.0.21 => 6.0.21 
    @storybook/vue: ^6.0.21 => 6.0.21 

**Additional context**
Package `@types/react` came as deps for `@types/react-color` and `@types/react-syntax-highlighter`

If delete types `rm -rf ./node_modules/@types/react`, everything works like a charm.

Or i can use `path` in `tsconfig` to solve this. 
```
compilerOptions.path = {
      "react": ["./nothins.d.ts"],
}
```

### PR DESCRIPTION
**Pull request by unrevised6419**
Discussion: https://github.com/johnsoncodehk/volar/discussions/592

Using `@storybook/vue` JSX Runtime types and Volar extension conflicts with `@types/react` from Storybook

```shell
❯ npm ls @types/react
my-project@0.0.0 /Users/iamandrewluca/Projects/my-project
└─┬ @storybook/addon-essentials@6.5.4
  └─┬ @storybook/addon-actions@6.5.4
    └─┬ @storybook/components@6.5.4
      └─┬ @types/react-syntax-highlighter@11.0.5
        └── @types/react@18.0.9
```

Closes #12505

### CODE REVIEW

**Comment by yannbf** [comment]
Hey @iamandrewluca thanks a lot for your contribution! This is a quite tricky one, @ndelangen could you assist? Thanks!

**Comment by ndelangen** [comment]
This seems the same as https://github.com/storybookjs/storybook/pull/18425

**Comment by shilman** [comment]
@iamandrewluca thanks so much for your patience on this & the original contribution. it looks like the contents of this PR are already contained in `next` so i'm closing it now.

**Comment by mockingjet** [comment]
Hi, `@types/react` is still installed with pnpm

```json
"devDependencies": {
    "@babel/core": "^7.18.10",
    "@storybook/addon-actions": "^6.5.12",
    "@storybook/addon-essentials": "^6.5.12",
    "@storybook/addon-interactions": "^6.5.12",
    "@storybook/addon-links": "^6.5.12",
    "@storybook/builder-vite": "^0.2.2",
    "@storybook/mdx2-csf": "^0.0.3",
    "@storybook/testing-library": "^0.0.13",
    "@storybook/vue3": "^6.5.12",
    "babel-loader": "^8.2.5",
    "vue-loader": "^16.8.3"
}
```

**Comment by iamandrewluca** [comment]
@mockingjet please read the conversation above

**Comment by mockingjet** [comment]
I read it, but I don't get it. v6.5.12 has this fix, right? I still get `@types/react` installed

**Comment by iamandrewluca** [comment]
It was [fixed](https://github.com/storybookjs/storybook/pull/18425) in v7 only. I think v6 won't get the fix.

**Comment by mockingjet** [comment]
Cool. I thought this fix was merged in May, it should be in the current version. Never thought of `next` branch means v7. Thanks

**Comment by Timakra** [comment]
Can we cherry pick this fix to have it fixed in 6.5.* too and not only v7

**Comment by noamori25** [comment]
I think it will be great to cherry-pick this fix also to 6.5 version.

**Comment by mockingjet** [comment]
I pernoally hope the v7 released beta as soon as possible.
And I do feel like the team take a negative attitude towards v6, which I think it's a good thing meaning that they can put more efforts on v7-beta

**Comment by shilman** [comment]
@yuval-agritask Sorry to hear about the upgrade headaches. I'll discuss with @ndelangen and see whether we can do anything here.

**Comment by alexandrkrucheniuk** [comment]
also faced the issue described by @yuval-agritask
