### ISSUE TITLE
"wrappedWellKnownSymbolModule.f is not a function" after upgrade from 6.1.21 to 6.2.9

### ISSUE THREAD

**Issue by kdong007** [storybookjs/storybook#14763]
**Describe the bug**
everything was working at 6.1.21. After upgrade to 6.2.9, `yarn storybook` can't properly launch.

![Screen Shot 2021-04-29 at 10 23 15 AM](https://user-images.githubusercontent.com/26269173/116592626-104e4f00-a8d5-11eb-909a-9235b18f0fac.png)

**To Reproduce**

![Screen Shot 2021-04-29 at 10 25 08 AM](https://user-images.githubusercontent.com/26269173/116592729-2eb44a80-a8d5-11eb-9619-996c13a96906.png)

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.20.1/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ~6.2.9 => 6.2.9 
    @storybook/addon-console: ^1.2.3 => 1.2.3 
    @storybook/addon-essentials: ~6.2.9 => 6.2.9 
    @storybook/addon-links: ~6.2.9 => 6.2.9 
    @storybook/react: ~6.2.9 => 6.2.9 

**Additional context**

**Comment by shilman** [comment]
Do you have a repro repo you can share?
