### ISSUE TITLE
Uncaught TypeError: context.stylis is not a function

### ISSUE THREAD

**Issue by bernatfortet** [storybookjs/storybook#6093]
**Describe the bug**
Storybook build but in the window (localhost:6006) I get the following console error:
`Uncaught TypeError: context.stylis is not a function`

![image](https://user-images.githubusercontent.com/390010/54384608-db79d200-4651-11e9-8aa6-a4942f30ceb8.png)

**System:**
 - OS: MacOS (High Sierra)
 - Device: MacBook Pro mid 105
 - Browser: chrome
 - Framework: react
 - Addons: [if relevant]
 - Version: 5.0.1

**Comment by shilman** [comment]
Looks like you need to wrap your stories with some provider that adds `stylis` to the context, e.g.

```js
addDecorator(storyFn => <SomeProvider>{storyFn()}</SomeProvider>)
```

**Comment by Armanio** [comment]
Could you share code snippet for reproduce this?

**Comment by Jack-Works** [comment]
Also have this problem

**Comment by njarin** [comment]
I also had this problem on a storybook project. I deleted the contents of the .cache folder in the repo and restarted my storybook server. The error is gone. Not sure what caused the issue to manifest in the first place though.

**Comment by RickyMarou** [comment]
Getting the same problem here. Not using stylis in my project and clearing the `.cache` folder did not help :(

**Comment by bernatfortet** [comment]
@Armanio, sorry for the late response. I think I did the same @RickyMarou and it fixed my issue.
Hard to create a snippet for that.

**Comment by tsaiDavid** [comment]
I actually got this same issue when upgrading from v4 -> v5. I'm using Lerna + Yarn Workspaces and just had to delete *all* `node_modules/` and was good to go

**Comment by Jack-Works** [comment]
remove node_modules solve my problem
