### ISSUE TITLE
Unexpected module issues with babel-loader after upgrading @babel/core to v7.12.7

### ISSUE THREAD

**Issue by ChristianIvicevic** [storybookjs/storybook#13203]
**Describe the bug**
After upgrading `@babel/core` from v7.12.3 to v7.12.7 an error occurs while attempting to load `babel-loader` even though it is already supplied by `create-react-app`.

In #13108 it was noticed that CRA supplies its own `babel-loader` at v8.1.0 and the one added by Storybook (v8.2.0) can be removed to use the pinned CRA version. However after upgrading `@babel/core` as mentioned above the following error occurs when invoking `yarn storybook`:

```
ERR! Error: Cannot find module 'babel-loader'
ERR! Require stack:
ERR! - [project]/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js
ERR! - [project]/node_modules/@storybook/core/dist/server/presets.js
ERR! - [project]/node_modules/@storybook/core/dist/server/config.js
ERR! - [project]/node_modules/@storybook/core/dist/server/build-static.js
ERR! - [project]/node_modules/@storybook/core/server.js
ERR! - [project]/node_modules/@storybook/react/dist/server/index.js
ERR! - [project]/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
ERR!     at Object.webpack ([project]/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js:143:27)
ERR!     at [project]/node_modules/@storybook/core/dist/server/presets.js:259:28
ERR!     at async startPreview ([project]/node_modules/@storybook/core/dist/server/dev-server.js:367:23)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer ([project]/node_modules/@storybook/core/dist/server/dev-server.js:454:28)
ERR!     at async buildDevStandalone ([project]/node_modules/@storybook/core/dist/server/build-dev.js:311:33)
ERR!     at async buildDev ([project]/node_modules/@storybook/core/dist/server/build-dev.js:374:3)
ERR!  Error: Cannot find module 'babel-loader'
ERR! Require stack:
ERR! - [project]/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js
ERR! - [project]/node_modules/@storybook/core/dist/server/presets.js
ERR! - [project]/node_modules/@storybook/core/dist/server/config.js
ERR! - [project]/node_modules/@storybook/core/dist/server/build-static.js
ERR! - [project]/node_modules/@storybook/core/server.js
ERR! - [project]/node_modules/@storybook/react/dist/server/index.js
ERR! - [project]/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:94:19)
ERR!     at Object.webpack ([project]/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js:143:27)
ERR!     at [project]/node_modules/@storybook/core/dist/server/presets.js:259:28
ERR!     at async startPreview ([project]/node_modules/@storybook/core/dist/server/dev-server.js:367:23)
ERR!     at async Promise.all (index 0)
ERR!     at async storybookDevServer ([project]/node_modules/@storybook/core/dist/server/dev-server.js:454:28)
ERR!     at async buildDevStandalone ([project]/node_modules/@storybook/core/dist/server/build-dev.js:311:33)
ERR!     at async buildDev ([project]/node_modules/@storybook/core/dist/server/build-dev.js:374:3) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '[project]/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js',
ERR!     '[project]/node_modules/@storybook/core/dist/server/presets.js',
ERR!     '[project]/node_modules/@storybook/core/dist/server/config.js',
ERR!     '[project]/node_modules/@storybook/core/dist/server/build-static.js',
ERR!     '[project]/node_modules/@storybook/core/server.js',
ERR!     '[project]/node_modules/@storybook/react/dist/server/index.js',
ERR!     '[project]/node_modules/@storybook/react/bin/index.js'
ERR!   ]
ERR! }
```

This can only be fixed by adding `babel-loader` at v8.1.0 explicitly back as a dependency. Unfortunately this forces me to adjust my dependency update bot once again to never update the loader and is slightly noisy.

**Comment by promethyttrium** [comment]
Gotta love how `npx sb init` touted as the "easy" way install storybook in an existing React project (https://storybook.js.org/docs/react/get-started/install) and it proceeds to immediately corrupts the React project by adding a babel-loader dependency the prevents React from running. And the only way to "fix" is to manually remove it, blowing away your `node_modules` folder and re `npm install`. Boy that sure inspires confidence...

**Comment by shilman** [comment]
Closing as dupe to #4764 cc @mrmckeb @tooppaaa
