### PR TITLE
Revert: Nuxt support

### PR DESCRIPTION
**Pull request by ndelangen**
## What I did

Reverted this change:  https://github.com/storybookjs/storybook/pull/26884/files

During QA before 8.2 release it was detected that it wasn't working correctly.

Reverting it and revisiting later unblocks the release, as we don't want to ship something that's broken.

We can release this feature, once fully working, in a patch release.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [ ] integration tests
- [ ] end-to-end tests

#### Manual testing

_This section is mandatory for all contributions. If you believe no manual test is necessary, please state so explicitly. Thanks!_

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

**Review by valentinpalkovic — APPROVED** [review]

**Comment by tobiasdiez** [comment]
What error did you experience? I just tried it with 8.2.0-beta.1 and it worked flawlessly for me. What is the procedure to get this back in?

Btw, pinging me and @chakAs3 during the QA and in this PR would have been appreciated. I spent quite some time trying to debug why `storybook init` is not working with the released 8.2.0 in a nuxt project, only to realize that my PR has been reverted last minute.

**Comment by valentinpalkovic** [comment]
Hi @tobiasdiez 

We definitely planned to let you know about the revert. I apologize that we forget about it at the end.

We have tested the initialization of Nuxt in 8.2.0-beta.0 and the following errors occurred:

NPM:
npx nuxi@latest init (select npm)cd ./nuxt-appnpx storybook@8.2.0-beta.0 init

Initialization succeeded, but while starting Storybook, I got the following error:

```
✘ [ERROR] Could not resolve "#app/entry"

    node_modules/@storybook-vue/nuxt/dist/preview.mjs:7:31:
      7 │   const nuxtApp = () => import('#app/entry').then((m) => m.default);
        ╵                                ~~~~~~~~~~~~

  You can mark the path "#app/entry" as external to exclude it from the bundle, which will remove
  this error and leave the unresolved path in the bundle. You can also add ".catch()" here to handle
  this failure at run-time instead of bundle-time.
```

PNPM:
npx nuxi@latest init (select pnpm)cd ./nuxt-appnpx storybook@8.2.0-beta.0 init
The following error pops up during init

```

✔ Installing Storybook dependencies

     Error: Cannot find @storybook-vue/nuxt/package.json, Error: Cannot find module '@storybook-vue/nuxt/package.json'
Require stack:
- /Users/valentinpalkovic/.npm/_npx/30b66e50c619b15f/node_modules/storybook/dist/generate.cjs
- /Users/valentinpalkovic/.npm/_npx/30b66e50c619b15f/node_modules/storybook/bin/index.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Function.resolve (node:internal/modules/helpers:188:19)
    at getRendererDir (/Users/valentinpalkovic/.npm/_npx/30b66e50c619b15f/node_modules/storybook/dist/generate.cjs:60:11624)
    at templatePath (/Users/valentinpalkovic/.npm/_npx/30b66e50c619b15f/node_modules/storybook/dist/generate.cjs:62:2146)
    at copyTemplateFiles (/Users/valentinpalkovic/.npm/_npx/30b66e50c619b15f/node_modules/storybook/dist/generate.cjs:62:3340)
    at async baseGenerator (/Users/valentinpalkovic/.npm/_npx/30b66e50c619b15f/node_modules/storybook/dist/generate.cjs:108:782)
```

**Comment by tobiasdiez** [comment]
The first issue has been fixed https://github.com/nuxt-modules/storybook/issues/670. Not sure about the second one. When did you tested it?

**Comment by valentinpalkovic** [comment]
5th of July with Storybook 8.2.0-beta.0

**Comment by tobiasdiez** [comment]
okay, then I suppose it is fixed now as well with the latest release. 
What is the plan to revert this revert?

We do still have a few issues that are reported (https://github.com/nuxt-modules/storybook/issues). But it would be very helpful for us to have the init script working for nuxt projects so that we get better reproductions and users can more easily test the latest version.

**Comment by valentinpalkovic** [comment]
I will create a PR on Monday and if CI is green and initialization works I will merge it.
