### ISSUE TITLE
Default props with handsontable causes infinite loading

### ISSUE THREAD

**Issue by AnnyCaroline** [storybookjs/storybook#14247]
**Describe the bug**
When using the Storybook with the [handsontable](https://handsontable.com/), my Storybook stopped working, showing the error `Uncaught TypeError: toISOString is not a function`

**To Reproduce**
I created a small repository to demonstrate the bug: https://github.com/AnnyCaroline/react-storybook-typescript/tree/with-handsontable. It has two important commits.

**In the first one**, [500cd23582](https://github.com/AnnyCaroline/react-storybook-typescript/tree/500cd23582bb5cf92deda3beef099f0870c18910), everything is working fine. We have two components and two stories. [`MyTable`](https://github.com/AnnyCaroline/react-storybook-typescript/blob/500cd23582bb5cf92deda3beef099f0870c18910/src/components/MyTable/MyTable.tsx) is a very simple component, that receives no props - [see its story](https://github.com/AnnyCaroline/react-storybook-typescript/blob/500cd23582bb5cf92deda3beef099f0870c18910/src/components/MyTable/MyTable.stories.tsx)

The **second one** - [WithProps](https://github.com/AnnyCaroline/react-storybook-typescript/blob/500cd23582bb5cf92deda3beef099f0870c18910/src/components/WithProps/WithProps.tsx) is also very simple, and receives a string prop.

The second commit modificates these both components. `MyTable` is modificated to use `HotTable` (from handsontable lib), and `WIthProps` starts receiving a default value for the `tooltipPosition` prop.

It is worth mentioning that in this commit, the stories work separately, but together they cause this bug

**Expected behavior**
Storybook should work fine with the second commit too. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17753656/111330407-a9d7df00-864e-11eb-8df1-f7554e752410.png)

**Code snippets**
Repository: https://github.com/AnnyCaroline/react-storybook-typescript/tree/with-handsontable

**System**
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 12.1.0 - ~/.nvm/versions/node/v12.1.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.1.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 86.0
  npmPackages:
    @storybook/addon-docs: 6.1.21 => 6.1.21 
    @storybook/react: 6.1.21 => 6.1.21

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
