### PR TITLE
NextJS: Add compatibility with nextjs `13.5`

### LINKED ISSUE #24234: [Bug]: `@storybook/nextjs` does not work with Next v13.5.1
### Describe the bug

After upgrading to Next v13.5.1, `@storybook/nextjs` fails to start.

```
Error: Cannot find module 'next/dist/shared/lib/router-context'
Require stack:
- ./node_modules/@storybook/nextjs/dist/preset.js
- ./node_modules/@storybook/core-common/dist/index.js
- ./node_modules/@storybook/telemetry/dist/index.js
- ./node_modules/@storybook/cli/dist/generate.js
- ./node_modules/@storybook/cli/bin/index.js
- ./node_modules/storybook/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._resolveFilename (./node_modules/esbuild-register/dist/node.js:4799:36)
    at Function.resolve (node:internal/modules/cjs/helpers:127:19)
    at scopedResolve (./node_modules/@storybook/nextjs/dist/preset.js:1:9988)
    at addScopedAlias (./node_modules/@storybook/nextjs/dist/preset.js:1:9703)
    at configureRouting (./node_modules/@storybook/nextjs/dist/preset.js:1:13928)
    at Object.webpackFinal (./node_modules/@storybook/nextjs/dist/preset.js:1:29114)
    at async Object.webpack (./node_modules/@storybook/builder-webpack5/dist/presets/custom-webpack-preset.js:1:3214)
    at async starter (./node_modules/@storybook/builder-webpack5/dist/index.js:1:4658)
    at async Module.start (./node_modules/@storybook/builder-webpack5/dist/index.js:1:8521)
    at async storybookDevServer (./node_modules/@storybook/core-server/dist/index.js:101:8374)
    at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:116:3013)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:101:4155)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:471:401)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:473:225)
```

### To Reproduce

Upgrade Next to latest v13.5.1. Install latest of `@storybook/nextjs`, v7.4.2.

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Edge: 117.0.2045.35
    Safari: 16.6
  npmPackages:
    @storybook/addon-a11y: ~7.4.2 => 7.4.2 
    @storybook/addon-coverage: ~0.0.9 => 0.0.9 
    @storybook/addon-designs: ~7.0.5 => 7.0.5 
    @storybook/addon-essentials: ~7.4.2 => 7.4.2 
    @storybook/addon-interactions: ~7.4.2 => 7.4.2 
    @storybook/addon-links: ~7.4.2 => 7.4.2 
    @storybook/addon-styling: ~1.3.7 => 1.3.7 
    @storybook/blocks: ~7.4.2 => 7.4.2 
    @storybook/manager-api: ~7.4.2 => 7.4.2 
    @storybook/nextjs: ~7.4.2 => 7.4.2 
    @storybook/react: ~7.4.2 => 7.4.2 
    @storybook/testing-library: ^0.2.1 => 0.2.1 
    @storybook/theming: ~7.4.2 => 7.4.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ndelangen**
Closes https://github.com/storybookjs/storybook/issues/24234

## What I did

I modified the webpack config creation code to add compatibility with nextjs 13.5

Files we need to alias got moved, and thus i created a mapping of nextjs version to files to map.

#### The changes in this PR are covered in the following automated tests:
- [ ] stories
- [ ] unit tests
- [x] integration tests
- [x] end-to-end tests

#### Manual testing

- Create a sandbox with nextjs 13.5
- Start storybook in this sandbox

Expect things to work, storybook should start and show up correctly.

### Documentation

- [ ] Add or update documentation reflecting your changes
- [ ] If you are deprecating/removing a feature, make sure to update
      [MIGRATION.MD](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

## Checklist for Maintainers

- [ ] When this PR is ready for testing, make sure to add `ci:normal`, `ci:merged` or `ci:daily` GH label to it to run a specific set of sandboxes. The particular set of sandboxes can be found in `code/lib/cli/src/sandbox-templates.ts`
- [ ] Make sure this PR contains **one** of the labels below:
   <details>
     <summary>Available labels</summary>

     - `bug`: Internal changes that fixes incorrect behavior.
     - `maintenance`: User-facing maintenance tasks.
     - `dependencies`: Upgrading (sometimes downgrading) dependencies.
     - `build`: Internal-facing build tooling & test updates. Will not show up in release changelog.
     - `cleanup`: Minor cleanup style change. Will not show up in release changelog.
     - `documentation`: Documentation **only** changes. Will not show up in release changelog.
     - `feature request`: Introducing a new feature.
     - `BREAKING CHANGE`: Changes that break compatibility in some way with current major version.
     - `other`: Changes that don't fit in the above categories.
   
   </details>

### 🦋 Canary release

This PR does not have a canary release associated. You can request a canary release of this pull request by mentioning the `@storybookjs/core` team here.

_core team members can create a canary release [here](https://github.com/storybookjs/storybook/actions/workflows/canary-release-pr.yml) or locally with `gh workflow run --repo storybookjs/storybook canary-release-pr.yml --field pr=<PR_NUMBER>`_

### CODE REVIEW

File: code/frameworks/nextjs/src/dependency-map.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
+import type { Configuration as WebpackConfig } from 'webpack';
+import semver from 'semver';
+import { getNextjsVersion, addScopedAlias } from './utils';
+
+const mapping: Record<string, Record<string, string>> = {
+  '<11.1.0': {
+    'next/dist/next-server/lib/router-context': 'next/dist/next-server/lib/router-context',
+  },
+  '>11.1.0': {
```
Comment (yannbf) [inline code/frameworks/nextjs/src/dependency-map.ts:9]:
```suggestion
  '>=11.1.0': {
```

**Review by yannbf — APPROVED** [review]

**Comment by kebearry** [comment]
Hi there, I am currently using nextjs 14 and I need to use storybook version 6 because of legacy issues. I faced this problem ERR! Error: Cannot find module 'next/dist/shared/lib/router-context' when i tried to use storybook-addon-next. Is there any recommendations?

**Comment by valentinpalkovic** [comment]
Hi @kebearry 

Sorry to hear that! Storybook 6 and 7 are not maintained anymore. Can you elaborate why you can't upgrade to Storybook 8?
