### ISSUE TITLE
theming.lighten is not a function

### ISSUE THREAD

**Issue by cwhenderson20** [storybookjs/storybook#7633]
**Describe the bug**
Opening the Storybook server menu crashes the page with the error `theming.lighten is not a function`

**To Reproduce**
1. Run storybook server (v5.2.0-beta.18)
2. Open the "..." menu
3. Observe crash

**Expected behavior**
The overlay menu should open. It worked correctly in 5.1.9.

**Code snippets**
Stacktrace:
```
vendors~main.2e0b73dc29e6ccc3125a.bundle.js:28325 Uncaught TypeError: (0 , _theming.lighten) is not a function
    at vendors~main.2e0b73dc29e6ccc3125a.bundle.js:28325
    at handleInterpolation (vendors~main.2e0b73dc29e6ccc3125a.bundle.js:915)
    at serializeStyles (vendors~main.2e0b73dc29e6ccc3125a.bundle.js:1007)
    at vendors~main.2e0b73dc29e6ccc3125a.bundle.js:1366
    at updateContextConsumer (vendors~main.2e0b73dc29e6ccc3125a.bundle.js:45794)
    at beginWork (vendors~main.2e0b73dc29e6ccc3125a.bundle.js:45982)
    at performUnitOfWork (vendors~main.2e0b73dc29e6ccc3125a.bundle.js:49622)
    at workLoop (vendors~main.2e0b73dc29e6ccc3125a.bundle.js:49662)
    at HTMLUnknownElement.callCallback (vendors~main.2e0b73dc29e6ccc3125a.bundle.js:30459)
    at Object.invokeGuardedCallbackDev (vendors~main.2e0b73dc29e6ccc3125a.bundle.js:30509)
```

**System:**
```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
    Safari: 12.1.1
```

**Additional context**
I started my project with the stable channel of Storybook for React Native, which, as of today, used version 5.1.9. However, I had to switch to 5.2 due to #4716. After reinstalling, clearing caches, and rerunning builds, I have consistently seen the above issue.

Of note: when I first set up with 5.1.9, I had to manually install `@storybook/theming` as per #5817.
