### ISSUE TITLE
Storybook does not work with RN0.59.+

### ISSUE THREAD

**Issue by MaxToyberman** [storybookjs/storybook#6452]
**Describe the bug**
Unable to load findSymlinksPaths: Cannot find module 'react-native/local-cli/util/findSymlinksPaths'

error: unknown option `--projectRoots'

**To Reproduce**
1. Upgrade to latest react-native version
2. run storybook start -p 7007 | react-native start --projectRoot storybook

**Additional context**
I think the problem is because the path is wrong, now the cli is from @react-community/cli

**Comment by shilman** [comment]
Which version of storybook?

**Comment by jgcmarins** [comment]
I've solved this adding `react-dom` as devDep
and then adding this to `metro.config.js`:
```js
const path = require('path');

module.exports = {
  projectRoot: path.resolve(__dirname, '.'),

  watchFolders: [
    path.resolve(__dirname, 'node_modules'),
  ],

  resolver: {
    // https://github.com/facebook/metro/issues/1#issuecomment-453450709
    extraNodeModules: new Proxy({}, {
      get: (target, name) => path.join(process.cwd(), `node_modules/${name}`),
    }),
  },

  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};
```

**Comment by MaxToyberman** [comment]
@shilman 3.4.12 latest on npm

**Comment by shilman** [comment]
Oh wow. Any reason you're not upgrading to 4.x or 5.1-alpha.x (other than that upgrading can be a pain in the neck)?

**Comment by MaxToyberman** [comment]
@shilman actually i have tried to use version 4.1.16 which is using "airbnb-js-shims" which is using "promise.prototype.finally" . and then i have another error "finally is undefined".

**Comment by shilman** [comment]
@benoitdion @Gongreg have you seen this `airbnb-js-shims` issue?

@MaxToyberman Perhaps @jgcmarins workaround will work for you on 3.4? If not, I suggest trying to upgrade to 5.1-alpha. All active development is going on there, so you're much more likely to get help if you're running latest. We just don't have the resources to go back and support RN59 in old versions of storybook unless it's community-contributed.

**Comment by MaxToyberman** [comment]
@shilman  the same problem on 5.1-alpha, my dependecies:
```

"@storybook/addon-actions": "5.0.6",
    "@storybook/addon-knobs": "5.0.6",
    "@storybook/addon-ondevice-knobs": "4.1.16",
    "@storybook/addon-ondevice-notes": "4.1.16",
    "@storybook/addons": "5.0.6",
    "@storybook/react-native": "5.1.0-alpha.24",
```

**Comment by shilman** [comment]
@MaxToyberman I don't think this will solve the problem, but in general keep all your `@storybook/*` to the same version (in this case `5.1.0-alpha.24`). Also did you follow the 5.1 migration instructions: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#react-native-server

**Comment by MaxToyberman** [comment]
@shilman I have created a new empty project and added storybook with : npx -p @storybook/cli sb init --type react_native

then i write  : 

```
    fetch("https://google.com")
      .then(res => {})
      .catch(e => {
        console.log("finally");
      })
      .finally(() => {
        console.log("finally");
      });
```
i get this error : 

![Simulator Screen Shot - iPhone 6 - 2019-04-10 at 14 43 39](https://user-images.githubusercontent.com/11058371/55875950-11ea3480-5b9f-11e9-9c6c-d82d7e068f4e.png)

**Comment by MaxToyberman** [comment]
The solution for me was to modify package.json to : 


```
    "@storybook/addon-actions": "4.0.11",
    "@storybook/addon-knobs": "4.0.11",
    "@storybook/addon-links": "4.0.11",
    "@storybook/addon-ondevice-knobs": "4.1.16",
    "@storybook/addon-ondevice-notes": "4.0.11",
    "@storybook/addons": "4.0.11",
    "@storybook/react-native": "4.0.11",
```

**Comment by benoitdion** [comment]
@MaxToyberman are you still seeing the issue with the latest 5.1 RC?
