### ISSUE TITLE
addon-docs: incorrect path in mdx-compiler-plugin, manual configuration flow fails

### ISSUE THREAD

**Issue by bdefore** [storybookjs/storybook#15265]
**Describe the bug**

Manual configuration of MDX compilation is documented here https://github.com/storybookjs/storybook/tree/next/addons/docs#manual-configuration. It states to use:

`import mdxCompiler from '@storybook/addon-docs/mdx-compiler-plugin';`

and configure in webpack config:

```
      {
        test: /\.stories\.mdx$/,
        use: [
          'babel-loader',
          {
            loader: '@mdx-js/loader',
            options: { compilers: [mdxCompiler({})] },
          },
        ],
      },
```

This works in 6.2.9 but as of 6.3.0-rc.7 an error occurs during build using this:

`Error: Cannot find module './dist/cjs/mdx/mdx-compiler-plugin'`

In this file is an export that points to a path that does not exist in the installed @storybook/addon-docs: https://github.com/storybookjs/storybook/blob/next/addons/docs/mdx-compiler-plugin.js#L1

In jest-transform-mdx.js it imports from a different path: https://github.com/storybookjs/storybook/blob/next/addons/docs/jest-transform-mdx.js#L6

Note that in an attempt to workaround this error by removing the import and option from the @mdx-js/loader options, an `Error: Unexpected default export without title: undefined` error occurs, such as described in https://github.com/storybookjs/storybook/issues/15097 so the compiler plugin is necessary.

A workaround for now is to follow what the jest transform is doing and instead:

`import { createCompiler as mdxCompiler } from '@storybook/csf-tools/mdx'`

Ideally we can update the import path in mdx-compiler-plugin so that existing flows still work with 6.3.0

**To Reproduce**

No time to set up a new project at the moment, but let me know if it's necessary.

**System**

Environment Info:

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.51
    Firefox: 57.0.4
    Safari: 14.1.1
```

**Additional context**

Discussion on discord: https://discord.com/channels/486522875931656193/501692020226654208/854711192006295552

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-rc.8 containing PR #15266 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by bdefore** [comment]
confirmed rc8 now works with existing documented import guidance. 👏
