### ISSUE TITLE
[Bug]: `@storybook/nextjs` does not work with Next v13.5.1

### ISSUE THREAD

**Issue by mririgoyen** [storybookjs/storybook#24234]
### Describe the bug

After upgrading to Next v13.5.1, `@storybook/nextjs` fails to start.

```
Error: Cannot find module 'next/dist/shared/lib/router-context'
Require stack:
- ./node_modules/@storybook/nextjs/dist/preset.js
- ./node_modules/@storybook/core-common/dist/index.js
- ./node_modules/@storybook/telemetry/dist/index.js
- ./node_modules/@storybook/cli/dist/generate.js
- ./node_modules/@storybook/cli/bin/index.js
- ./node_modules/storybook/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._resolveFilename (./node_modules/esbuild-register/dist/node.js:4799:36)
    at Function.resolve (node:internal/modules/cjs/helpers:127:19)
    at scopedResolve (./node_modules/@storybook/nextjs/dist/preset.js:1:9988)
    at addScopedAlias (./node_modules/@storybook/nextjs/dist/preset.js:1:9703)
    at configureRouting (./node_modules/@storybook/nextjs/dist/preset.js:1:13928)
    at Object.webpackFinal (./node_modules/@storybook/nextjs/dist/preset.js:1:29114)
    at async Object.webpack (./node_modules/@storybook/builder-webpack5/dist/presets/custom-webpack-preset.js:1:3214)
    at async starter (./node_modules/@storybook/builder-webpack5/dist/index.js:1:4658)
    at async Module.start (./node_modules/@storybook/builder-webpack5/dist/index.js:1:8521)
    at async storybookDevServer (./node_modules/@storybook/core-server/dist/index.js:101:8374)
    at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:116:3013)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:101:4155)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:471:401)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:473:225)
```

### To Reproduce

Upgrade Next to latest v13.5.1. Install latest of `@storybook/nextjs`, v7.4.2.

### System

```bash
Environment Info:

  System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Edge: 117.0.2045.35
    Safari: 16.6
  npmPackages:
    @storybook/addon-a11y: ~7.4.2 => 7.4.2 
    @storybook/addon-coverage: ~0.0.9 => 0.0.9 
    @storybook/addon-designs: ~7.0.5 => 7.0.5 
    @storybook/addon-essentials: ~7.4.2 => 7.4.2 
    @storybook/addon-interactions: ~7.4.2 => 7.4.2 
    @storybook/addon-links: ~7.4.2 => 7.4.2 
    @storybook/addon-styling: ~1.3.7 => 1.3.7 
    @storybook/blocks: ~7.4.2 => 7.4.2 
    @storybook/manager-api: ~7.4.2 => 7.4.2 
    @storybook/nextjs: ~7.4.2 => 7.4.2 
    @storybook/react: ~7.4.2 => 7.4.2 
    @storybook/testing-library: ^0.2.1 => 0.2.1 
    @storybook/theming: ~7.4.2 => 7.4.2
```

**Comment by adarsh-drishya** [comment]
but please tell me how did you guys make the react server component work? @ziishaned @mririgoyen

**Comment by purplenimbus** [comment]
> next/dist/shared/lib/router-context

What file did you change?

To add some context it seems like this is a path issue 'next/dist/shared/lib/router-context'; doesn't seem to be referenced

**Comment by adarsh-drishya** [comment]
same its not mentioned anywhere in my repo

**Comment by purplenimbus** [comment]
updated my package.json to 

```
"dependencies": {
    "next": "13.4.19",
  },
```
removed the `^` and did a `yarn install` and it works

**Comment by adarsh-drishya** [comment]
but there should a fix for this 13.5.1 i want to know that

**Comment by purplenimbus** [comment]
There should be , i'm pretty sure the path needs to be updated

**Comment by Wkasel** [comment]
> After updating the import statement from `import { RouterContext } from 'next/dist/shared/lib/router-context';` to `import { RouterContext } from 'next/dist/shared/lib/router-context.shared-runtime';` fixed the issue for me.

I thought we didn't need that line anymore?

Does your preview file look something like this? I still see the issue.

```typescript
import { RouterContext } from 'next/dist/shared/lib/router-context.shared-runtime';

const preview = {
  parameters: {
    nextRouter: {
      Provider: RouterContext.Provider,
    },
    nextjs: {
      router: {
        path: '/',
        asPath: '/',
        query: {},
      },
    },
  },
};

export default preview
```

**Comment by shilman** [comment]
@ndelangen Looks like we just need to update the import (and fallback to the old location for backwards compatibility?) https://github.com/storybookjs/storybook/issues/24234#issuecomment-1726353377

**Comment by 0xMemoryGrinder** [comment]
I used `npx storybook@latest init` a few hours ago and I don't have the path in the preview.ts
I think the workaround would not work in fresh install @shilman.

Here is my preview.ts content : 
```typescript
import type { Preview } from "@storybook/react";

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/,
      },
    },
  },
};

export default preview;```

**Comment by adarsh-drishya** [comment]
@shilman  this workaround does not work. this is a sev1 issue. I want to update next to 13.5.1 asap 
![image](https://github.com/storybookjs/storybook/assets/108795907/c2184efc-3b18-4655-9e4f-5e89765dfac5)

**Comment by yannbf** [comment]
Hey everyone! Thanks for reporting this, we know about the regression and are currently working on a fix for it. We will release it as soon as we can today.

**Comment by ndelangen** [comment]
I'm in the process of doing a patch-release, with this fix in.

**Comment by AdrianFahrbach** [comment]
Thank you very much for fixing this so fast! A patch within 24 hours is not the norm and definitely great reaction time.

**Comment by adarsh-drishya** [comment]
yeah just installed and checked it still has the same issue. @ndelangen

**Comment by mririgoyen** [comment]
I can confirm that the newly published version of `7.4.3` of Storybook and all of its addons has fixed the issue.

To be clear, I was not doing anything special with the Router context within Storybook and Next is being used simply to build components that can utilize things such as `next/font`, `next/image`, and `next/link`. It seems like there are more advanced use-cases being reported here as well.` However, the simple act of using `@storybook/nextjs` as the framework was fixed in the patch that was pushed.

IMO, the advanced use-cases being defined here need a solid reproduction repo and likely a new issue to address them.

**Comment by ndelangen** [comment]
I have run the following reproduction:

- I run `yarn create next-app`
- Follow the guide of the next CLI, and chose all the default options
- I `cd` into the `my-app` directory
- I run `npm storybook@latest init`
- I go though the storybook CLI and chose all the default options
- I run `yarn storybook`
- The browser opens, everything looks good
- I run `yarn build-storybook`
- I host the `storybook-static` directory
- I open it in my browser, everything looks good.

I conclude that can't reproduce this anymore myself on my machine on sb `7.4.1`.

If this problem indeed does persist, I'd need more help, there might be something I'm missing.

**Comment by Tottzi** [comment]
Okay, I had to fire an `npm upgrade @storybook/nextjs` so it went forward, but other issue came up. I'll report it in other place. :)

**Comment by vitorsbmendes** [comment]
Guys, it works again. You have to remove previously generated files and re-run it. For me , since I was generating it again, just did the "npx create-next-app@latest" (or just go to your current project without storybook in it) and then "npx storybook@latest init". It works, thanks for solving it so quickly!

**Comment by ndelangen** [comment]
Thank you for the positive feedback @vitorsbmendes @Tottzi

**Comment by PasterZOOM** [comment]
Thanks, updating all storybook modules fixed it!!!

**Comment by terrymun** [comment]
Just want to drop a note of thanks to the storybook team: thanks for looking into this bug in such a timely manner! After upgrading storybook-related dependencies to 7.4.3, I can verify that it works perfectly with `next@13.5.2` 🎊 g

**Comment by ndelangen** [comment]
It's great to hear such positive feedback @terrymun ❤️

**Comment by BnAmN** [comment]
I would like to add one more thing since I wasn't able to fix the error using the described methods in this issue. Even after upgrading and re-initializing, the error still occurred once I restored my configuration.  
Turned out I had an error in my `main.ts` regarding the `alias` configuration, where I forget to retain the `alias` from the original configuration:

```diff
    /* (...) */
    config.resolve = {
      ...config.resolve,
      ...{
        alias: {
+          ...config.resolve?.alias,
          '@': [path.resolve(__dirname, '../src/')]
        },
        /* (...) */
      }
    }
    /* (...) */
```

I can't remember if this was an old example from the documentation or if I just forgot it in the first place, but it didn't seem to be a problem in earlier version.

I hope this helps someone else who made the same mistake.

**Comment by markky21** [comment]
I updated storybook deps and this was not resolving my problem. 
I am using 'next-router-mock' and this has the direct import of 'next/dist/shared/lib/router-context'

What worked for me, and I am not happy with that, was adding to `main.js` a new alias like below:
`
config.resolve.alias = {
      ...(config.resolve.alias ?? {}),
     /* ... */
      'next/dist/shared/lib/router-context': require.resolve(
        './router-context.js'
      ),
    };`
`
and created in the same folder file `router-context.js` with content is taken form previous nextjs version:
`
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "RouterContext", {
    enumerable: true,
    get: function() {
        return RouterContext;
    }
});
const _interop_require_default = require("@swc/helpers/_/_interop_require_default");
const _react = /*#__PURE__*/ _interop_require_default._(require("react"));
const RouterContext = _react.default.createContext(null);
if (process.env.NODE_ENV !== "production") {
    RouterContext.displayName = "RouterContext";
}

//# sourceMappingURL=router-context.js.map
`

**Comment by yannbf** [comment]
Hey @markky21 seems like a bug in `next-router-mock`, maybe open an issue in their repo?

**Comment by usrrname** [comment]
I'm like the n'th person late to the party... looking at the trail

**Comment by gvillenave** [comment]
As many people have mentioned in https://github.com/vercel/next.js/issues/55620, the error below is seen when upgrading either Storybook to 7.4.3+ and/or upgrading Next.js to 13.5+.

```Error: Can't resolve 'react-dom/test-utils' in '...node_modules/@testing-library/react/dist/@testing-library'```

@shilman can we reopen this issue and investigate further?

**Comment by philwolstenholme** [comment]
> `Error: Can't resolve 'react-dom/test-utils' in '...node_modules/@testing-library/react/dist/@testing-library'`

I'm seeing this too with the latest stable versions of both Next and Storybook (as of today)

**Comment by federicocappellotto97** [comment]
I'm still having error: Module not found: Error: Can't resolve 'next/dist/shared/lib/router-context'
"next": "13.5.4-canary.8"
"storybook": "7.4.5"

**Comment by ndelangen** [comment]
@valentinpalkovic maybe we need to add something extra for this canary version of nextjs to this file:
https://github.com/storybookjs/storybook/blob/855ab5faadb13b22b36bb2dbae304ebbb099d34d/code/frameworks/nextjs/src/dependency-map.ts#L1-L36

**Comment by vladern** [comment]
I'm still having this error: Failed to build the preview Error: Cannot find module 'next/dist/shared/lib/router-context'
```
"storybook": "^7.5.0-alpha.3",
"next": "^13.5.2",
```

**Comment by AKiranB** [comment]
The issue was fixed for me with `npm upgrade @storybook/nextjs `

Thanks!

**Comment by vladern** [comment]
> The issue was fixed for me with `npm upgrade @storybook/nextjs `
> 
> Thanks!

THanks, it worked for me :)

**Comment by federicocappellotto97** [comment]
Still having the same problem even with all dependencies to 7.4.6
`ModuleNotFoundError: Module not found: Error: Can't resolve 'next/dist/shared/lib/router-context' in './node_modules/@storybook/nextjs/dist'`

**Comment by adarsh-drishya** [comment]
@ndelangen Hi sir, earlier the issue was fixed, but somehow the builds are now breaking.
maybe related to the new version i upgraded to. can we fix once and for all the upcoming releasing that might come.
right now i am on     "next": "13.5.2-canary.0",

**Comment by adarsh-drishya** [comment]
> Still having the same problem even with all dependencies to 7.4.6 `ModuleNotFoundError: Module not found: Error: Can't resolve 'next/dist/shared/lib/router-context' in './node_modules/@storybook/nextjs/dist'`

just dont use a canary version it will work, follow this convention https://github.com/storybookjs/storybook/issues/24234#issuecomment-1743214495

**Comment by federicocappellotto97** [comment]
> > Still having the same problem even with all dependencies to 7.4.6 `ModuleNotFoundError: Module not found: Error: Can't resolve 'next/dist/shared/lib/router-context' in './node_modules/@storybook/nextjs/dist'`
> 
> just dont use a canary version it will work, follow this convention [#24234 (comment)](https://github.com/storybookjs/storybook/issues/24234#issuecomment-1743214495)

I need to use a canary version of next, since in the stable release next 13.5.4 some things are not working in my project, like images optimization. They fixed it in 13.5.4-canary.1

**Comment by jonasmarco** [comment]
> I'm facing a error bit different with a NextJS latest app
> 
> > @next/env@13.5.3
> 
> ![image](https://user-images.githubusercontent.com/19959770/271088271-4fa44820-9c35-445d-b7b9-418a1faadac8.png)

working now 😀 `npx storyboox@latest init` storybook@7.4.6

**Comment by gvillenave** [comment]
I found the root cause of the error below:
`Error: Can't resolve 'react-dom/test-utils' in '...node_modules/@testing-library/react/dist/@testing-library'`

The default Webpack configuration of Storybook resolves `react-dom` to `@storybook/react-dom-shim`, which doesn't have a shim for `test-utils`. I managed to resolve this by overriding the Webpack config in `.storybook/main`:
```
  webpackFinal: async (config) => {
    config.resolve = config.resolve || {};
    config.resolve.alias = config.resolve.alias || {};
    config.resolve.alias["@testing-library/react"] = "@storybook/testing-library";
// OR
	config.resolve.alias["react-dom"] = "react-dom";
    return config;
  },
```

I think the right fix here would be to add a `test-utils` shim in `@storybook/react-dom-shim`, I'm opening a new issue to track that.

**Comment by adam-qantas** [comment]
I'm using Next 13 app directory for routing. After `npm upgrade @storybook/nextjs` I was still getting error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'next/dist/shared/lib/router-context' in './node_modules/@storybook/nextjs/dist'
```

Adding the following to`storybook/preview.js` resolved it for me:

```
  nextjs: {
    appDirectory: true,
  }
```

**Comment by Cloud11PL** [comment]
Getting the same error with `"next": "13.5.5-canary.7"`

**Comment by akshayjai1** [comment]
installing alpha version of storybook, helped understand the error, 

it was because I was using @testing-library/react in a storybook file, instead it should have been @storybook/testing-library
 
to import {within}

I am using latest version of next js namely 
```
"next": "13.5.4",
        "react": "18.2.0",
        "react-dom": "^18.2.0",
        
"@storybook/addon-actions": "^7.5.0-alpha.6",
        "@storybook/addon-essentials": "^7.5.0-alpha.6",
        "@storybook/addon-interactions": "^7.5.0-alpha.6",
        "@storybook/addon-links": "^7.5.0-alpha.6",
        "@storybook/jest": "^0.2.3",
        "@storybook/nextjs": "^7.5.0-alpha.6",
        "@storybook/react": "^7.5.0-alpha.6",
        "@storybook/test-runner": "^0.13.1-next.1",
        "@storybook/testing-library": "^0.2.2",
        "@testing-library/dom": "^9.3.3",
        "@testing-library/jest-dom": "^6.1.3",
        "@testing-library/react": "^14.0.0",
        "@testing-library/react-hooks": "^8.0.1",
        "@types/jest": "^29.5.5",
        "@types/lodash": "^4.14.199",
        "@types/node": "^20.8.4",
        
```

**Comment by BnAmN** [comment]
I encountered the same problem again with the LTS version of Node (18.x):
```
SB_BUILDER-WEBPACK5_0002 (WebpackInvocationError): Module not found: Error: Can't resolve 'next/dist/shared/lib/router-context' in './.storybook'
```

With Node 20 I was able to resolve the error using the fix I described here: https://github.com/storybookjs/storybook/issues/24234#issuecomment-1730209029

For the LTS version I had to explicitly add the following to my `alias` configuration in `main.ts`:

```diff
    /* (...) */
    config.resolve = {
      ...config.resolve,
      ...{
        alias: {
          ...config.resolve?.alias,
+         'next/dist/shared/lib/router-context': 'next/dist/shared/lib/router-context.shared-runtime',
          '@': [path.resolve(__dirname, '../src/')]
        },
        /* (...) */
      }
    }
    /* (...) */
```

Depending on the installed Version of Next this can be different according to:  
https://github.com/storybookjs/storybook/blob/855ab5faadb13b22b36bb2dbae304ebbb099d34d/code/frameworks/nextjs/src/dependency-map.ts#L1-L36

I have not yet paid closer attention to why the alias was not registered in the first place.

**Comment by ndelangen** [comment]
@valentinpalkovic could you check if something changed in nextjs land (again)?

**Comment by valentinpalkovic** [comment]
@BnAmN Which Storybook version do you use? Do you use the latest 7.5.0 version?

**Comment by BnAmN** [comment]
@valentinpalkovic: Yes, I'm using:
- `next@13.5.5`
- `storybook/*@7.5.0`

Explicitly running `npm upgrade @storybook/nextjs` didn‘t fix the issue again.  
But I was a bit confused that the Node version affected this issue, since the same code was building fine using Node 20.x.

**Comment by TenetMax** [comment]
If anyone on `12.x` versions ends up here from seeing the error: 
> Error: Cannot find module 'next/dist/shared/lib/app-router-context'   

I see it (without possible resolution) on `12.1.5` and `12.1.6`. It is fixable in `12.1.7-canary.8`  (with a variant of the error, `Module not found: Error: Can't resolve 'next/dist/shared/lib/router-context.shared-runtime'`) with the following webpack config in .storybook/main.js:
```
  webpack: (config) => {
    config.resolve = config.resolve || {};
    config.resolve.modules = config.resolve.modules || [];
    config.resolve.alias = {
      ...config.resolve.alias,
      "next/dist/shared/lib/router-context.shared-runtime":
        "next/dist/shared/lib/router-context",
      "next/dist/shared/lib/head-manager-context.shared-runtime":
        "next/dist/shared/lib/head-manager-context",
    };
    return config;
  },
```

The issue also does not appear at all (no configuration needed) in `12.3.3`, which I was able to upgrade directly to, but YMMV there.

**Comment by selrond** [comment]
working for me on
```json
"next": "^13.5.6",
"@storybook/nextjs": "^7.6.3",
```

**Comment by hwride** [comment]
> ```js
> 'next/dist/shared/lib/router-context': require.resolve(
>         './router-context.js'
>       ),
> ```

I am also seeing it on 12.1.6.

**Comment by hwride** [comment]
> @hwride Just fyi: We will drop Next.js < v13.5 support in Storybook 8. Upgrading Next.js to 13.5 or higher will very likely fix the issue.

Great, thanks for letting me know.

**Comment by evakill** [comment]
> The issue also does not appear at all (no configuration needed) in 12.3.3, which I was able to upgrade directly to, but YMMV there.


this worked for me, thank you @TenetMax !!!

**Comment by njblore** [comment]
I'm still seeing this issue with next v13.5.1 and @storybook/nextjs v7.6.7 - has the fix gone in?

**Comment by Damo1155** [comment]
For anyone experiencing this on the configuration below it's possibly being caused by Webpack:

- NextJS:  `v14.*`
- Storybook: `v8.*`
- Typescript: `v5.4.5` 
 
Not saying this will fix it for everyone but we've had to add the following to `.storybook/main.ts` and may be down to some of the packages we are using.

```typescript
  async webpackFinal(config) {
    config.module = {
      rules: [
        ...(config.module?.rules ?? []),
        {
          test: /\.(ts|tsx)$/,
          use: [
            {
              loader: 'ts-loader',
              options: {
                transpileOnly: true,
              },
            },
          ],
        },
      ],
    };

    return config;
  },
```

**Comment by kebearry** [comment]
Hi there, I am currently using nextjs 14 and I need to use storybook version 6 because of legacy issues. I faced this problem ERR! Error: Cannot find module 'next/dist/shared/lib/router-context' when i tried to use storybook-addon-next. Is there any recommendations?

**Comment by jaumamyfront-ender** [comment]
guys in my case (very similar) i got the issue like this -->Module not found: Can't resolve 'next/dist/shared/lib/router-context'
https://nextjs.org/docs/messages/module-not-found
Import trace for requested module:
./node_modules/next-translate-routes/index.js
./pages/_app.tsx
   Using external babel configuration from /Users/bogdan/Documents/work/landing/.babelrc.js
 ⨯ ./node_modules/next-translate-routes/react/withTranslateRoutes.js:38:1
Module not found: Can't resolve 'next/dist/shared/lib/router-context'
https://nextjs.org/docs/messages/module-not-found
Import trace for requested module:
./node_modules/next-translate-routes/index.js
./pages/_app.tsx
 GET / 500 in 7289ms
=========================
i find my solution is for this problem
-->go to node_modules-->folder next-translate-routes-->folder react--->try to find files with name withTranslateRoutes.js:38:1-->go to line 38.1 and put instead old import line this-->var router_context_1 = require("next/dist/shared/lib/router-context.shared-runtime");-->then kill your terminal--then delete folder ~/.next-->then try  to yarn dev or whatever you use as pm
=========================
![Zrzut ekranu 2024-09-2 o 15 39 41 (2)](https://github.com/user-attachments/assets/bf955893-39a0-4884-882f-ba5648c307e8)
